import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import { Workbook } from "@oai/artifact-tool";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const queuePath = path.join(root, "data", "labeling_queue.csv");
const outputDir = path.join(root, "data", "ai_labeling");

// Each row was assigned individually under the Prototype SIF Potential Labeling Framework.
// Tuple: [label code, confidence, evidence taxonomy code].
const decisions = {
  "OSHA-SIR-20241110304": ["U", 0.55, "BIO"],
  "OSHA-SIR-20231211139": ["S", 0.88, "ENTANGLE"],
  "OSHA-SIR-20231211320": ["S", 0.84, "MACH_ENTANGLE"],
  "OSHA-SIR-2024032254": ["N", 0.90, "PINCH_LOCAL"],
  "OSHA-SIR-2024032164": ["S", 0.78, "ROLL_HEAVY"],
  "OSHA-SIR-2024053785": ["S", 0.92, "CRUSH"],
  "OSHA-SIR-2024043227": ["N", 0.94, "PINCH_LOCAL"],
  "OSHA-SIR-2024010257": ["S", 0.73, "LIFT"],
  "OSHA-SIR-2024021458": ["S", 0.98, "ENTANGLE"],
  "OSHA-SIR-2024010653": ["U", 0.58, "LADDER_TOOL"],
  "OSHA-SIR-2024010158": ["S", 0.96, "HIGH_RIG"],
  "OSHA-SIR-2024021317": ["S", 0.72, "ENTANGLE"],
  "OSHA-SIR-2025077460": ["S", 0.84, "HIGH_RIG"],
  "OSHA-SIR-20251010530": ["N", 0.97, "LOW_STEP"],
  "OSHA-SIR-20251010647": ["S", 0.99, "EXCAVATION"],
  "OSHA-SIR-2025032579": ["N", 0.72, "VEHICLE_LOCAL"],
  "OSHA-SIR-2024076029": ["N", 0.83, "PINCH_LOCAL"],
  "OSHA-SIR-2025021422": ["N", 0.70, "PINCH_LOCAL"],
  "OSHA-SIR-2024043008": ["S", 0.94, "LIFT_CRUSH"],
  "OSHA-SIR-2024010753": ["N", 0.87, "PINCH_LOCAL"],
  "OSHA-SIR-2024098564": ["N", 0.86, "PINCH_LOCAL"],
  "OSHA-SIR-2024010903": ["N", 0.94, "PINCH_LOCAL"],
  "OSHA-SIR-2024032181": ["S", 0.99, "DROPPED_OBJECT_LINE"],
  "OSHA-SIR-2024021751": ["U", 0.57, "HOT_LINE"],
  "OSHA-SIR-20231211158": ["S", 0.99, "FIRE"],
  "OSHA-SIR-2024042848": ["S", 0.99, "HOT_SLURRY"],
  "OSHA-SIR-2024010090": ["N", 0.88, "PINCH_LOCAL"],
  "OSHA-SIR-2024087293": ["N", 0.94, "SAME_FALL"],
  "OSHA-SIR-2024021562": ["S", 0.99, "ELECTRIC_ARC"],
  "OSHA-SIR-2024010671": ["S", 0.90, "ELECTRIC_SHOCK"],
  "OSHA-SIR-2024010135": ["U", 0.61, "WINCH_HAND"],
  "OSHA-SIR-2024065474": ["S", 0.95, "CRUSH"],
  "OSHA-SIR-2024087059": ["S", 0.99, "EXPLOSION"],
  "OSHA-SIR-2024076038": ["S", 0.99, "EXPLOSION"],
  "OSHA-SIR-20251111514": ["S", 0.99, "EXPLOSION"],
  "OSHA-SIR-2025099616": ["S", 0.97, "PRESSURE"],
  "OSHA-SIR-2024043602": ["S", 0.99, "PRESSURE"],
  "OSHA-SIR-2025043738": ["S", 0.99, "PRESSURE"],
  "OSHA-SIR-2024010031": ["S", 0.91, "CHEM_PRESSURE"],
  "OSHA-SIR-2024065726": ["S", 0.99, "ELECTRIC_ARC"],
  "OSHA-SIR-2024098520": ["S", 0.82, "ELECTRIC_SHOCK"],
  "OSHA-SIR-2025021704": ["U", 0.55, "COLD"],
  "OSHA-SIR-2024054626": ["S", 0.76, "HEAT"],
  "OSHA-SIR-2024054307": ["N", 0.96, "SAME_FALL"],
  "OSHA-SIR-2024098181": ["N", 0.70, "SAME_FALL"],
  "OSHA-SIR-2025032196": ["N", 0.86, "PINCH_LOCAL"],
  "OSHA-SIR-2024076349": ["N", 0.84, "HAND_LOAD"],
  "OSHA-SIR-2024010071": ["N", 0.97, "SAME_FALL"],
  "OSHA-SIR-2025043710": ["S", 0.76, "MACH_ENTANGLE"],
  "OSHA-SIR-2024010091": ["U", 0.60, "STRUCK_UNKNOWN"],
  "OSHA-SIR-2024065117": ["S", 0.99, "FALL_HIGH"],
  "OSHA-SIR-2025021221": ["N", 0.82, "FALL_LOW"],
  "OSHA-SIR-2024098218": ["S", 0.98, "TRENCH_EDGE"],
  "OSHA-SIR-2024076300": ["S", 0.73, "PRESSURE_FALL"],
  "OSHA-SIR-20251010185": ["S", 0.91, "TOXIC_FALL"],
  "OSHA-SIR-2024054631": ["N", 0.78, "FALL_LOW"],
  "OSHA-SIR-2025032450": ["N", 0.91, "PINCH_LOCAL"],
  "OSHA-SIR-2024065810": ["S", 0.84, "SMALL_FIRE"],
  "OSHA-SIR-20241110910": ["S", 0.99, "EXPLOSION"],
  "OSHA-SIR-20231211334": ["S", 0.99, "EXPLOSION"],
  "OSHA-SIR-2024054058": ["S", 0.98, "FIRE"],
  "OSHA-SIR-2024054402": ["S", 0.99, "FIRE"],
  "OSHA-SIR-2025021642": ["S", 0.90, "CLOTHING_FIRE"],
  "OSHA-SIR-20231211033": ["S", 0.98, "FIRE"],
  "OSHA-SIR-2024065298": ["S", 0.99, "ELECTRIC_LINE"],
  "OSHA-SIR-2024032536": ["S", 0.99, "ELECTRIC_LINE"],
  "OSHA-SIR-2025021232": ["U", 0.60, "TOXIC_INGEST"],
  "OSHA-SIR-2025043700": ["S", 0.99, "TOXIC_GAS"],
  "OSHA-SIR-20251010189": ["S", 0.97, "TOXIC_GAS"],
  "OSHA-SIR-2024098252": ["N", 0.90, "PINCH_LOCAL"],
  "OSHA-SIR-2024065679": ["N", 0.98, "MANUAL_CUT"],
  "OSHA-SIR-2025032390": ["S", 0.78, "ROTATING_IMPROPER"],
  "OSHA-SIR-2024021406": ["S", 0.80, "STORED_ENERGY_BAR"],
  "OSHA-SIR-20251010320": ["S", 0.88, "TORQUE_RECOIL"],
  "OSHA-SIR-2024021188": ["S", 0.80, "WINCH_SCAFFOLD"],
  "OSHA-SIR-20241211383": ["U", 0.62, "GRATE_CRUSH"],
  "OSHA-SIR-2025043243": ["S", 0.99, "EXPLOSIVES"],
  "OSHA-SIR-2024109936": ["S", 0.93, "VEHICLE_COLLISION"],
  "OSHA-SIR-2025076412": ["S", 0.98, "VEHICLE_COLLISION"],
  "OSHA-SIR-2025088413": ["S", 0.96, "VEHICLE_EJECTION"],
  "OSHA-SIR-20241211880": ["S", 0.95, "VEHICLE_OVERTURN"],
  "OSHA-SIR-2025088531": ["S", 0.94, "VEHICLE_OVERTURN"],
  "OSHA-SIR-2024010047": ["S", 0.96, "FALL_HIGH"],
  "OSHA-SIR-2024010648": ["S", 0.99, "FALL_HIGH"],
  "OSHA-SIR-2024021513": ["N", 0.75, "FALL_LOW"],
  "OSHA-SIR-2025032724": ["N", 0.78, "FALL_LOW"],
  "OSHA-SIR-2024042949": ["S", 0.99, "FALL_HIGH"],
  "OSHA-SIR-2024032554": ["U", 0.55, "FALL_UNKNOWN"],
  "OSHA-SIR-2025010866": ["N", 0.99, "OVEREXERTION"],
  "OSHA-SIR-2024053968": ["S", 0.97, "VEHICLE_RUNOVER"],
  "OSHA-SIR-2024021303": ["S", 0.99, "VEHICLE_CRUSH"],
  "OSHA-SIR-2025087666": ["S", 0.99, "VEHICLE_CRUSH"],
  "OSHA-SIR-2024109364": ["N", 0.68, "PINCH_LOCAL"],
  "OSHA-SIR-2025055136": ["S", 0.94, "VEHICLE_RUNOVER"],
  "OSHA-SIR-2024054584": ["S", 0.99, "VEHICLE_RUNOVER"],
  "OSHA-SIR-20231211376": ["S", 0.91, "DROPPED_LOAD"],
  "OSHA-SIR-2025099342": ["N", 0.93, "STAIRS_LOW"],
  "OSHA-SIR-2025087910": ["N", 0.99, "STRUCK_LOW"],
  "OSHA-SIR-20251010231": ["S", 0.76, "EYE_IMPALE"],
  "OSHA-SIR-2024010118": ["S", 0.98, "ENERGY_PROJECTILE"],
  "OSHA-SIR-2025032361": ["S", 0.99, "PRESSURE"],
  "OSHA-SIR-2024054394": ["N", 0.84, "DROPPED_OBJECT_LOCAL"],
  "OSHA-SIR-2024021191": ["S", 0.80, "STORED_TENSION"],
  "OSHA-SIR-2024098993": ["S", 0.96, "PIPE_SWING"],
  "OSHA-SIR-2024098429": ["N", 0.99, "PINCH_LOCAL"],
  "OSHA-SIR-2024032434": ["U", 0.60, "DOOR_HEAD"],
  "OSHA-SIR-2024021072": ["N", 0.76, "DROPPED_OBJECT_LOCAL"],
  "OSHA-SIR-2024043641": ["S", 0.98, "RIG_COLLAPSE"],
  "OSHA-SIR-2024010267": ["U", 0.60, "FALLING_UNKNOWN"],
  "OSHA-SIR-2024010850": ["N", 0.94, "PINCH_LOCAL"],
  "OSHA-SIR-2024021688": ["S", 0.99, "CRANE_FALL"],
  "OSHA-SIR-20241211220": ["S", 0.99, "HIGH_RIG"],
  "OSHA-SIR-2024054149": ["N", 0.93, "PINCH_LOCAL"],
  "OSHA-SIR-2024076231": ["N", 0.91, "DROPPED_OBJECT_LOCAL"],
  "OSHA-SIR-2024054524": ["N", 0.80, "DROPPED_OBJECT_LOCAL"],
  "OSHA-SIR-20241110530": ["N", 0.92, "DROPPED_OBJECT_LOCAL"],
  "OSHA-SIR-2024075952": ["S", 0.99, "TIPPING_EQUIP"],
  "OSHA-SIR-2025021658": ["S", 0.99, "TIPPING_EQUIP"],
  "OSHA-SIR-2024076544": ["N", 0.84, "DROPPED_OBJECT_LOCAL"],
  "OSHA-SIR-2024087451": ["N", 0.82, "DROPPED_OBJECT_LOCAL"],
  "OSHA-SIR-2024054144": ["U", 0.58, "FALLING_UNKNOWN"],
  "OSHA-SIR-2024032201": ["S", 0.91, "DROPPED_LOAD"],
  "OSHA-SIR-2025077110": ["S", 0.76, "DROPPED_HEAVY"],
  "OSHA-SIR-2025032244": ["S", 0.96, "LINE_WHIP"],
  "OSHA-SIR-2024087108": ["S", 0.80, "WEDGE_PROJECTILE"],
  "OSHA-SIR-2024064969": ["S", 0.97, "PRESSURE"],
  "OSHA-SIR-2024065079": ["S", 0.96, "ENERGY_PROJECTILE"],
  "OSHA-SIR-2025032146": ["S", 0.98, "DROPPED_LOAD"],
  "OSHA-SIR-2024032595": ["S", 0.98, "VEHICLE_RUNOVER"],
  "OSHA-SIR-2024109712": ["N", 0.92, "PINCH_LOCAL"],
  "OSHA-SIR-2024053824": ["S", 0.73, "PLATE_ROLL"],
  "OSHA-SIR-2024021680": ["S", 0.75, "MACH_ENTANGLE"],
  "OSHA-SIR-2024054535": ["N", 0.70, "VALVE_HAND"],
  "OSHA-SIR-2024043650": ["S", 0.99, "MACHINE_RESTART"],
  "OSHA-SIR-2025099684": ["U", 0.62, "ROTATING_HAND"],
  "OSHA-SIR-2025054962": ["N", 0.70, "PINCH_LOCAL"],
  "OSHA-SIR-2024054385": ["S", 0.91, "DRILL_PIPE_BOW"],
  "OSHA-SIR-2025088501": ["N", 0.94, "PINCH_LOCAL"],
  "OSHA-SIR-2024076651": ["S", 0.96, "COUNTERWEIGHT"],
  "OSHA-SIR-2025021657": ["S", 0.92, "POWER_SWIVEL"],
  "OSHA-SIR-2024021480": ["N", 0.79, "PINCH_LOCAL"],
  "OSHA-SIR-2025010579": ["S", 0.79, "POWER_TONGS"],
  "OSHA-SIR-20241211244": ["S", 0.99, "SWING_RADIUS"],
  "OSHA-SIR-2024021495": ["N", 0.87, "PINCH_LOCAL"],
  "OSHA-SIR-2024098909": ["S", 0.73, "SUSPENDED_LOAD"],
  "OSHA-SIR-2024043057": ["S", 0.91, "SUSPENDED_LOAD"],
  "OSHA-SIR-2024065056": ["S", 0.72, "SUSPENDED_LOAD"],
  "OSHA-SIR-2024109910": ["N", 0.99, "OVEREXERTION"],
  "OSHA-SIR-2024010927": ["S", 0.98, "FIRE"],
  "OSHA-SIR-2025065306": ["S", 0.99, "CRANE_FIRE"],
  "OSHA-SIR-2025077257": ["S", 0.95, "FIRE"],
  "OSHA-SIR-2024043748": ["S", 0.84, "VENOMOUS_BITE"],
  "OSHA-SIR-2024109922": ["U", 0.55, "STEAM_AVOID"],
  "OSHA-SIR-20241211420": ["N", 0.98, "WALKING"],
  "OSHA-SIR-2016042900": ["S", 0.72, "ANIMAL_FORCE"],
  "OSHA-SIR-2016010940": ["N", 0.99, "OVEREXERTION"],
  "OSHA-SIR-2017065761": ["U", 0.50, "BIO"],
  "OSHA-SIR-20181111301": ["N", 0.96, "LOW_STEP"],
  "OSHA-SIR-2018010036": ["S", 0.99, "VEHICLE_CRUSH"],
  "OSHA-SIR-2016021145": ["S", 0.99, "VEHICLE_CRUSH"],
  "OSHA-SIR-2015020234": ["U", 0.60, "RIGGING_HAND"],
  "OSHA-SIR-2016075939": ["S", 0.96, "HIGH_RIG"],
  "OSHA-SIR-2015010093": ["N", 0.88, "PINCH_LOCAL"],
  "OSHA-SIR-20171010313": ["N", 0.88, "PINCH_LOCAL"],
  "OSHA-SIR-2015020796": ["S", 0.94, "TREE_CRUSH"],
  "OSHA-SIR-2017076668": ["S", 0.72, "SUPPORTED_LOAD"],
  "OSHA-SIR-2015020655": ["U", 0.59, "POWER_TONGS_HAND"],
  "OSHA-SIR-2015010296": ["N", 0.70, "PINCH_LOCAL"],
  "OSHA-SIR-2015010325": ["S", 0.72, "MACH_ENTANGLE"],
  "OSHA-SIR-2015052903": ["S", 0.94, "MACH_ENTANGLE"],
  "OSHA-SIR-2021021240": ["S", 0.98, "ENTANGLE"],
  "OSHA-SIR-2015010448": ["S", 0.76, "MACH_ENTANGLE"],
  "OSHA-SIR-20171110941": ["S", 0.99, "ENTANGLE"],
  "OSHA-SIR-2015010736": ["S", 0.70, "POWER_TONGS"],
  "OSHA-SIR-2016065162": ["N", 0.82, "PINCH_LOCAL"],
  "OSHA-SIR-2015030400": ["U", 0.60, "HIGH_RIG_HAND"],
  "OSHA-SIR-2015074326": ["S", 0.70, "RIG_SECTION"],
  "OSHA-SIR-2019065577": ["S", 0.91, "RIG_SECTION"],
  "OSHA-SIR-2015064026": ["S", 0.72, "MACH_ENTANGLE"],
  "OSHA-SIR-2017010049": ["N", 0.83, "PINCH_LOCAL"],
  "OSHA-SIR-2018077788": ["S", 0.91, "MACH_ENTANGLE"],
  "OSHA-SIR-2015031198": ["S", 0.72, "MACH_ENTANGLE"],
  "OSHA-SIR-2015031231": ["N", 0.90, "PINCH_LOCAL"],
  "OSHA-SIR-2016076722": ["S", 0.98, "MACHINE_CRUSH"],
  "OSHA-SIR-2015030594": ["S", 0.99, "MACH_ENTANGLE"],
  "OSHA-SIR-2018088265": ["S", 0.72, "ENTANGLE"],
  "OSHA-SIR-20171110662": ["U", 0.55, "EXCAVATION_STEP"],
  "OSHA-SIR-2022064891": ["S", 0.99, "HIGHWAY_COLLISION"],
  "OSHA-SIR-2017099315": ["S", 0.84, "BOAT_COLLISION"],
  "OSHA-SIR-2015010074": ["N", 0.91, "PINCH_LOCAL"],
  "OSHA-SIR-2015096726": ["S", 0.82, "SUSPENDED_LOAD"],
  "OSHA-SIR-2015010676": ["S", 0.99, "VEHICLE_CRUSH"],
  "OSHA-SIR-2015010726": ["N", 0.87, "PINCH_LOCAL"],
  "OSHA-SIR-2015041924": ["N", 0.78, "PINCH_LOCAL"],
  "OSHA-SIR-20161211967": ["U", 0.62, "CHAIN_TENSION"],
  "OSHA-SIR-20201211546": ["S", 0.75, "BUTANE_RELEASE"],
  "OSHA-SIR-2015063519": ["S", 0.99, "HOT_ASPHALT"],
  "OSHA-SIR-2018088899": ["S", 0.98, "STEAM_RELEASE"],
  "OSHA-SIR-2021020944": ["N", 0.90, "RING_CATCH"],
  "OSHA-SIR-2017054463": ["N", 0.99, "RING_CATCH"],
  "OSHA-SIR-2015010261": ["U", 0.58, "MACHINE_VAGUE"],
  "OSHA-SIR-2015042100": ["S", 0.96, "PRESSURE"],
  "OSHA-SIR-2015020682": ["U", 0.55, "TOOL_VAGUE"],
  "OSHA-SIR-2023086969": ["S", 0.99, "EXPLOSIVES"],
  "OSHA-SIR-2015063815": ["S", 0.99, "ELECTRIC_SHOCK"],
  "OSHA-SIR-2015021269": ["S", 0.98, "ELECTRIC_SHOCK"],
  "OSHA-SIR-2015118789": ["S", 0.99, "ELECTRIC_ARC"],
  "OSHA-SIR-2018033109": ["S", 0.99, "ENGULFMENT"],
  "OSHA-SIR-2015020050": ["S", 0.70, "ENTANGLE"],
  "OSHA-SIR-2019032433": ["S", 0.92, "ENTANGLE"],
  "OSHA-SIR-2015060215": ["S", 0.99, "ENTANGLE_FALL"],
  "OSHA-SIR-2015063352": ["S", 0.98, "ENTANGLE"],
  "OSHA-SIR-2017021205": ["S", 0.96, "EXCAVATION"],
  "OSHA-SIR-2017010858": ["S", 0.98, "CHEM_EXPLOSION"],
  "OSHA-SIR-2015031586": ["S", 0.99, "PRESSURE"],
  "OSHA-SIR-20161011139": ["S", 0.99, "PRESSURE"],
  "OSHA-SIR-2015074999": ["S", 0.99, "EXPLOSION"],
  "OSHA-SIR-2023087375": ["S", 0.98, "EXPLOSION"],
  "OSHA-SIR-2020032242": ["S", 0.99, "EXPLOSION"],
  "OSHA-SIR-2016021347": ["S", 0.96, "EXPLOSION"],
  "OSHA-SIR-2023031900": ["S", 0.99, "EXPLOSIVES"],
  "OSHA-SIR-2019021646": ["S", 0.97, "EXPLOSION"],
  "OSHA-SIR-2020054632": ["S", 0.99, "TANK_EXPLOSION"],
  "OSHA-SIR-2021053922": ["S", 0.99, "TANK_EXPLOSION"],
  "OSHA-SIR-2015031349": ["N", 0.80, "ENV_CONTACT"],
  "OSHA-SIR-2019054516": ["S", 0.94, "MUD_PRESSURE_EYE"],
  "OSHA-SIR-2019076859": ["U", 0.58, "CHEM_UNKNOWN"],
  "OSHA-SIR-2015064039": ["S", 0.72, "HEAT"],
  "OSHA-SIR-2015063562": ["S", 0.76, "HEAT"],
  "OSHA-SIR-2016010021": ["U", 0.55, "CHEM_UNKNOWN"],
  "OSHA-SIR-2015010056": ["U", 0.58, "BURN_UNKNOWN"],
  "OSHA-SIR-2015030112": ["U", 0.50, "COLLAPSE_UNKNOWN"],
  "OSHA-SIR-2021053666": ["S", 0.99, "HF_RELEASE"],
  "OSHA-SIR-2018032549": ["S", 0.98, "FALL_HIGH"],
  "OSHA-SIR-2019099922": ["S", 0.99, "FALL_HIGH"],
  "OSHA-SIR-2016043383": ["S", 0.99, "FALL_HIGH"],
  "OSHA-SIR-2019043879": ["S", 0.78, "STAIR_COLLAPSE"],
  "OSHA-SIR-2015053314": ["S", 0.73, "PLATFORM_COLLAPSE"],
  "OSHA-SIR-20171110629": ["U", 0.55, "FALL_UNKNOWN"],
  "OSHA-SIR-2019099329": ["S", 0.76, "PLATFORM_COLLAPSE"],
  "OSHA-SIR-2016088097": ["N", 0.88, "PINCH_LOCAL"],
  "OSHA-SIR-2020032012": ["S", 0.76, "RIG_PIPE_CRUSH"],
  "OSHA-SIR-2015020055": ["S", 0.91, "HEAVY_HEAD_STRIKE"],
  "OSHA-SIR-2015031384": ["S", 0.72, "DUMP_BOX"],
  "OSHA-SIR-2015118254": ["N", 0.95, "SAME_FALL"],
  "OSHA-SIR-2022032767": ["N", 0.92, "SAME_FALL"],
  "OSHA-SIR-2016032350": ["N", 0.90, "SAME_FALL"],
  "OSHA-SIR-2015107866": ["N", 0.86, "SAME_FALL"],
  "OSHA-SIR-2016109793": ["S", 0.74, "SHARP_PROTRUSION"],
  "OSHA-SIR-2015010271": ["S", 0.92, "SHARP_PROTRUSION"],
  "OSHA-SIR-2015021361": ["S", 0.86, "HOT_COKE"],
  "OSHA-SIR-2018010419": ["S", 0.75, "RIG_PIPE_CRUSH"],
  "OSHA-SIR-2015010181": ["N", 0.98, "SAME_FALL"],
  "OSHA-SIR-2021054085": ["S", 0.78, "SHARP_PROTRUSION"],
  "OSHA-SIR-2015010401": ["N", 0.97, "SAME_FALL"],
  "OSHA-SIR-2015107725": ["S", 0.95, "SUSPENDED_LOAD"],
  "OSHA-SIR-20161211930": ["N", 0.90, "PINCH_LOCAL"],
  "OSHA-SIR-2016099138": ["N", 0.88, "SAME_FALL"],
  "OSHA-SIR-2022021797": ["S", 0.99, "WATERJET"],
  "OSHA-SIR-2018055135": ["S", 0.91, "SHARP_PROTRUSION"],
  "OSHA-SIR-2020032237": ["S", 0.79, "MACH_ENTANGLE"],
  "OSHA-SIR-2015129881": ["S", 0.98, "LINE_SNAP_FALL"],
  "OSHA-SIR-2015010253": ["S", 0.97, "LINE_SNAP_FALL"],
  "OSHA-SIR-2019066062": ["S", 0.82, "VEHICLE_EJECTION"],
  "OSHA-SIR-2015118834": ["S", 0.99, "VEHICLE_EJECTION"],
  "OSHA-SIR-2015010700": ["S", 0.99, "FALL_HIGH"],
  "OSHA-SIR-2016109353": ["S", 0.99, "FALL_HIGH"],
  "OSHA-SIR-2022065392": ["S", 0.99, "FALL_HIGH"],
  "OSHA-SIR-2022043040": ["S", 0.99, "FALL_HIGH"],
  "OSHA-SIR-20191111947": ["S", 0.99, "FALL_HIGH"],
  "OSHA-SIR-2016054654": ["S", 0.98, "FALL_HIGH"],
  "OSHA-SIR-2021020886": ["S", 0.79, "HOT_PIT"],
  "OSHA-SIR-2020010577": ["S", 0.81, "OPEN_CELLAR"],
  "OSHA-SIR-2015063813": ["S", 0.99, "FALL_HIGH"],
  "OSHA-SIR-2016098830": ["U", 0.55, "HOLE_UNKNOWN"],
  "OSHA-SIR-2015010140": ["S", 0.99, "RAIL_COLLISION"],
  "OSHA-SIR-2015129168": ["N", 0.96, "SAME_FALL"],
  "OSHA-SIR-2017065650": ["S", 0.72, "UNSTABLE_SKIDS"],
  "OSHA-SIR-2015010363": ["N", 0.88, "SAME_FALL"],
  "OSHA-SIR-2017109605": ["N", 0.90, "PINCH_LOCAL"],
  "OSHA-SIR-2016065427": ["S", 0.99, "EXPLOSION"],
  "OSHA-SIR-2016010251": ["S", 0.99, "CONFINED_FIRE"],
  "OSHA-SIR-2017087880": ["S", 0.98, "FIRE"],
  "OSHA-SIR-2023021122": ["S", 0.98, "FIRE"],
  "OSHA-SIR-2016055851": ["S", 0.88, "FIRE_FALL"],
  "OSHA-SIR-2021086483": ["S", 0.70, "ANIMAL_FORCE"],
  "OSHA-SIR-2018032417": ["U", 0.55, "ASSAULT"],
  "OSHA-SIR-2018010452": ["S", 0.91, "CLOTHING_FIRE"],
  "OSHA-SIR-2015096851": ["S", 0.99, "FIRE"],
  "OSHA-SIR-2015010417": ["S", 0.98, "FIRE"],
  "OSHA-SIR-2015041925": ["S", 0.98, "FIRE"],
  "OSHA-SIR-2015010541": ["S", 0.99, "EXPLOSION"],
  "OSHA-SIR-2017010688": ["S", 0.99, "PRESSURE_FIRE"],
  "OSHA-SIR-2021021798": ["S", 0.99, "FIRE"],
  "OSHA-SIR-2015108004": ["S", 0.99, "ELECTRIC_LINE"],
  "OSHA-SIR-2017054249": ["S", 0.99, "ELECTRIC_LINE"],
  "OSHA-SIR-2016021597": ["S", 0.99, "ELECTRIC_LINE"],
  "OSHA-SIR-2021065283": ["S", 0.99, "ELECTRIC_LINE"],
  "OSHA-SIR-2015010522": ["S", 0.94, "ELECTRIC_SHOCK"],
  "OSHA-SIR-2018099765": ["S", 0.99, "ELECTRIC_LINE"],
  "OSHA-SIR-2015041995": ["S", 0.86, "POISON_INGEST"],
  "OSHA-SIR-2015107637": ["U", 0.40, "INHALATION_VAGUE"],
  "OSHA-SIR-2015096421": ["S", 0.96, "TOXIC_GAS"],
  "OSHA-SIR-2015010478": ["S", 0.94, "TOXIC_GAS"],
  "OSHA-SIR-2017043721": ["S", 0.99, "HF_RELEASE"],
  "OSHA-SIR-2019033190": ["S", 0.72, "POWER_TONGS"],
  "OSHA-SIR-2019021679": ["N", 0.97, "OVEREXERTION"],
  "OSHA-SIR-20171211664": ["S", 0.76, "LONG_ROD_RECOIL"],
  "OSHA-SIR-2016020995": ["N", 0.92, "HAMMER_HAND"],
  "OSHA-SIR-2019032243": ["S", 0.96, "TORQUE_RECOIL"],
  "OSHA-SIR-2017032812": ["N", 0.98, "GLASS_HAND"],
  "OSHA-SIR-2016087087": ["N", 0.76, "HAND_TOOL_BREAK"],
  "OSHA-SIR-20181111446": ["N", 0.97, "SAME_FALL"],
  "OSHA-SIR-2015010438": ["U", 0.58, "WRENCH_HAND"],
  "OSHA-SIR-2016098738": ["S", 0.72, "POWER_TONGS"],
  "OSHA-SIR-2015042463": ["N", 0.78, "BIO_MINOR"],
  "OSHA-SIR-20161010261": ["U", 0.55, "TOOL_VAGUE"],
  "OSHA-SIR-2016076185": ["N", 0.91, "PINCH_LOCAL"],
  "OSHA-SIR-2015020653": ["N", 0.95, "HAMMER_HAND"],
  "OSHA-SIR-2017054820": ["N", 0.77, "HAMMER_HAND"],
  "OSHA-SIR-2022020992": ["N", 0.91, "HAMMER_HAND"],
  "OSHA-SIR-2022032643": ["N", 0.94, "HAMMER_HAND"],
  "OSHA-SIR-20181010483": ["U", 0.55, "ASSAULT"],
  "OSHA-SIR-2015020647": ["S", 0.94, "VEHICLE_OVERTURN"],
  "OSHA-SIR-2020087443": ["S", 0.98, "VEHICLE_OVERTURN"],
  "OSHA-SIR-2015031131": ["S", 0.99, "HIGHWAY_ROLLOVER"],
  "OSHA-SIR-2019099280": ["S", 0.99, "HIGHWAY_ROLLOVER"],
  "OSHA-SIR-2019066117": ["S", 0.70, "ENTANGLE"],
  "OSHA-SIR-20191112157": ["N", 0.85, "PINCH_LOCAL"],
  "OSHA-SIR-20201110744": ["S", 0.99, "MOORING_SNAPBACK"],
  "OSHA-SIR-2015031447": ["U", 0.40, "REPORT_VAGUE"],
  "OSHA-SIR-2015010023": ["U", 0.48, "BURN_UNKNOWN"],
  "OSHA-SIR-2015031116": ["U", 0.35, "REPORT_VAGUE"],
  "OSHA-SIR-2017010232": ["U", 0.58, "VEHICLE_VAGUE"],
  "OSHA-SIR-2019076882": ["S", 0.97, "VEHICLE_EJECTION"],
  "OSHA-SIR-2018021180": ["S", 0.99, "VEHICLE_CRUSH"],
  "OSHA-SIR-2022010896": ["U", 0.62, "VEHICLE_VAGUE"],
  "OSHA-SIR-2015096299": ["S", 0.98, "VEHICLE_OVERTURN"],
  "OSHA-SIR-2022075823": ["S", 0.91, "VEHICLE_OVERTURN"],
  "OSHA-SIR-2015052971": ["S", 0.97, "CLOTHING_FIRE"],
  "OSHA-SIR-2018032178": ["N", 0.97, "SAME_FALL"],
  "OSHA-SIR-2015074344": ["S", 0.98, "FALL_HIGH"],
  "OSHA-SIR-2015030396": ["S", 0.99, "FALL_HIGH"],
  "OSHA-SIR-2015010739": ["S", 0.99, "FALL_HIGH"],
  "OSHA-SIR-2018065995": ["S", 0.99, "FALL_HIGH"],
  "OSHA-SIR-2015075090": ["S", 0.99, "FALL_HIGH"],
  "OSHA-SIR-2015010569": ["S", 0.75, "FALL_HIGH"],
  "OSHA-SIR-20171010193": ["S", 0.99, "DROPPED_LOAD_FALL"],
  "OSHA-SIR-2015010720": ["N", 0.70, "FALL_LOW"],
  "OSHA-SIR-2015064201": ["N", 0.68, "FALL_LOW"],
  "OSHA-SIR-2015010364": ["S", 0.99, "FALL_HIGH"],
  "OSHA-SIR-2015010054": ["S", 0.86, "DERRICK_FALL"],
  "OSHA-SIR-2017010402": ["S", 0.76, "RACK_COLLAPSE"],
  "OSHA-SIR-2019054755": ["S", 0.99, "DRILL_REAMER"],
  "OSHA-SIR-2015041930": ["S", 0.76, "PRESSURE_ESCAPE"],
  "OSHA-SIR-2015107932": ["S", 0.99, "TRAIN_ESCAPE"],
  "OSHA-SIR-2015010068": ["N", 0.97, "FALL_LOW"],
  "OSHA-SIR-2016076633": ["N", 0.84, "FALL_LOW"],
  "OSHA-SIR-20181011102": ["S", 0.99, "HIGH_RIG"],
  "OSHA-SIR-2019010476": ["S", 0.88, "STRUCTURE_FIRE"],
  "OSHA-SIR-2015118993": ["N", 0.98, "OVEREXERTION"],
  "OSHA-SIR-2019044020": ["N", 0.99, "OVEREXERTION"],
  "OSHA-SIR-2019099239": ["N", 0.99, "OVEREXERTION"],
  "OSHA-SIR-2015042299": ["N", 0.99, "OVEREXERTION"],
  "OSHA-SIR-2018077651": ["N", 0.99, "OVEREXERTION"],
  "OSHA-SIR-2015075200": ["S", 0.96, "VEHICLE_CRUSH"],
  "OSHA-SIR-2016021394": ["S", 0.99, "VEHICLE_RUNOVER"],
  "OSHA-SIR-2015118676": ["S", 0.99, "VEHICLE_RUNOVER"],
  "OSHA-SIR-2017010082": ["S", 0.99, "ROAD_PEDESTRIAN"],
  "OSHA-SIR-20171212048": ["S", 0.99, "ROAD_PEDESTRIAN"],
  "OSHA-SIR-2018054320": ["S", 0.99, "RAIL_CRUSH"],
  "OSHA-SIR-2015085625": ["S", 0.98, "VEHICLE_RUNOVER"],
  "OSHA-SIR-2015074428": ["S", 0.99, "VEHICLE_CRUSH"],
  "OSHA-SIR-2015030990": ["S", 0.98, "VEHICLE_CRUSH"],
  "OSHA-SIR-2018044142": ["S", 0.99, "VEHICLE_CRUSH"],
  "OSHA-SIR-2016010669": ["S", 0.97, "ROAD_PEDESTRIAN"],
  "OSHA-SIR-2020088291": ["S", 0.91, "LONG_PIPE_LOAD"],
  "OSHA-SIR-2017043241": ["S", 0.99, "TRAILER_ROLLOVER"],
  "OSHA-SIR-2015030379": ["S", 0.99, "VEHICLE_RUNOVER"],
  "OSHA-SIR-2015042422": ["S", 0.88, "ROAD_PEDESTRIAN"],
  "OSHA-SIR-20190910175": ["U", 0.60, "GOLF_CART_PIN"],
  "OSHA-SIR-2020043073": ["S", 0.99, "VEHICLE_RUNOVER"],
  "OSHA-SIR-2015030879": ["S", 0.99, "ROAD_PEDESTRIAN"],
  "OSHA-SIR-2020054454": ["S", 0.99, "ROAD_PEDESTRIAN"],
  "OSHA-SIR-2019032471": ["S", 0.95, "LOADER_PULL"],
  "OSHA-SIR-2021086899": ["S", 0.99, "VEHICLE_CRUSH"],
  "OSHA-SIR-2015107520": ["S", 0.99, "VEHICLE_OVERTURN"],
  "OSHA-SIR-2015096491": ["S", 0.92, "HIGHWAY_COLLISION"],
  "OSHA-SIR-20181010424": ["U", 0.58, "SMALL_VEHICLE_COLLISION"],
  "OSHA-SIR-2015075247": ["U", 0.45, "COLLAPSE_UNKNOWN"],
  "OSHA-SIR-2019044133": ["S", 0.99, "FIREARM"],
  "OSHA-SIR-2018065614": ["S", 0.99, "FIREARM"],
  "OSHA-SIR-2015041948": ["S", 0.99, "FIREARM_ASSAULT"],
  "OSHA-SIR-2015010318": ["N", 0.88, "PINCH_LOCAL"],
  "OSHA-SIR-2015010806": ["N", 0.97, "SAME_FALL"],
  "OSHA-SIR-2017088097": ["S", 0.74, "MACH_ENTANGLE"],
  "OSHA-SIR-2015010807": ["U", 0.58, "PRESSURE_WASHER"],
  "OSHA-SIR-2017109574": ["N", 0.98, "SAME_FALL"],
  "OSHA-SIR-20181010670": ["S", 0.94, "FIRE"],
  "OSHA-SIR-2015096294": ["S", 0.88, "VENOMOUS_BITE"],
  "OSHA-SIR-2017065482": ["S", 0.72, "SAW_CONTACT"],
  "OSHA-SIR-2016065127": ["S", 0.91, "LIFT_FAN"],
  "OSHA-SIR-20191111472": ["U", 0.40, "STRUCK_UNKNOWN"],
  "OSHA-SIR-20170412415": ["S", 0.80, "FORK_IMPALE"],
  "OSHA-SIR-2023054552": ["N", 0.95, "HAMMER_HAND"],
  "OSHA-SIR-2015010273": ["S", 0.91, "HIGH_RIG"],
  "OSHA-SIR-2018054817": ["N", 0.97, "SPLINTER"],
  "OSHA-SIR-2015031018": ["N", 0.72, "FALL_LOW"],
  "OSHA-SIR-2021108821": ["N", 0.76, "ROUGH_RIDE"],
  "OSHA-SIR-2015021157": ["S", 0.99, "WATERJET"],
  "OSHA-SIR-2015053786": ["S", 0.99, "WATERJET"],
  "OSHA-SIR-2020066088": ["S", 0.99, "PRESSURE"],
  "OSHA-SIR-2016099268": ["S", 0.99, "PRESSURE"],
  "OSHA-SIR-20191213024": ["S", 0.99, "PRESSURE_SHRAPNEL"],
  "OSHA-SIR-2016098458": ["S", 0.97, "PRESSURE_HOSE"],
  "OSHA-SIR-2018043604": ["S", 0.97, "STEAM_PROJECTILE"],
  "OSHA-SIR-2015063456": ["S", 0.78, "TORQUE_RECOIL"],
  "OSHA-SIR-2019043400": ["S", 0.72, "PUMP_PROJECTILE"],
  "OSHA-SIR-2015010658": ["S", 0.98, "PRESSURE"],
  "OSHA-SIR-2015010441": ["S", 0.96, "PRESSURE"],
  "OSHA-SIR-2017021801": ["S", 0.99, "CHAIN_SNAPBACK"],
  "OSHA-SIR-2015020241": ["S", 0.99, "PRESSURE"],
  "OSHA-SIR-2016054820": ["S", 0.80, "HYDRAULIC_PROJECTILE"],
  "OSHA-SIR-2018055172": ["S", 0.98, "PRESSURE"],
  "OSHA-SIR-2016043296": ["S", 0.75, "JACK_COLLAPSE"],
  "OSHA-SIR-20171110965": ["S", 0.72, "SUPPORTED_PLATFORM"],
  "OSHA-SIR-2015020518": ["S", 0.84, "PIPE_RACK_FALL"],
  "OSHA-SIR-2015042154": ["S", 0.90, "BOP_TIP"],
  "OSHA-SIR-2018033060": ["S", 0.94, "ENERGY_PROJECTILE"],
  "OSHA-SIR-2015042210": ["U", 0.58, "FALLING_UNKNOWN"],
  "OSHA-SIR-2015021118": ["S", 0.88, "DROPPED_LOAD"],
  "OSHA-SIR-2023087194": ["S", 0.99, "DROPPED_LOAD"],
  "OSHA-SIR-2015086176": ["S", 0.94, "UNDER_LOAD"],
  "OSHA-SIR-2015020759": ["S", 0.99, "RIG_FLOOR_COLLAPSE"],
  "OSHA-SIR-2021087009": ["N", 0.82, "PINCH_LOCAL"],
  "OSHA-SIR-2017010028": ["S", 0.82, "FORK_DROP"],
  "OSHA-SIR-2015129170": ["N", 0.88, "DROPPED_OBJECT_LOCAL"],
  "OSHA-SIR-2021075939": ["S", 0.70, "TUBING_BOUNCE"],
  "OSHA-SIR-2015010597": ["S", 0.97, "DROPPED_LOAD"],
  "OSHA-SIR-2018032413": ["S", 0.99, "DROPPED_LOAD"],
  "OSHA-SIR-20201211952": ["S", 0.99, "DROPPED_LOAD"],
  "OSHA-SIR-2015031426": ["S", 0.96, "CRANE_FALL"],
  "OSHA-SIR-2021119925": ["S", 0.99, "ROLLING_POLE"],
  "OSHA-SIR-2020076436": ["S", 0.99, "PLATFORM_COLLAPSE"],
  "OSHA-SIR-2015030582": ["N", 0.76, "DROPPED_OBJECT_LOCAL"],
  "OSHA-SIR-2016098843": ["S", 0.94, "UNDER_LOAD"],
  "OSHA-SIR-2016087391": ["S", 0.90, "DROPPED_LOAD"],
  "OSHA-SIR-20161211319": ["S", 0.70, "SUSPENDED_LOAD"],
  "OSHA-SIR-2021021108": ["N", 0.88, "DROPPED_OBJECT_LOCAL"],
  "OSHA-SIR-2015052822": ["S", 0.98, "DROPPED_LOAD"],
  "OSHA-SIR-2018021922": ["N", 0.90, "DROPPED_OBJECT_LOCAL"],
  "OSHA-SIR-2018066035": ["N", 0.70, "ROLLING_LOCAL"],
  "OSHA-SIR-2015118874": ["S", 0.72, "PLATFORM_PIPE"],
  "OSHA-SIR-2019011040": ["S", 0.82, "ROLLING_PIPE"],
  "OSHA-SIR-20181010628": ["S", 0.70, "ROLLING_PIPE"],
  "OSHA-SIR-2019099854": ["S", 0.98, "ROLLING_PIPE"],
  "OSHA-SIR-2016010758": ["S", 0.78, "WIRE_SNAP"],
  "OSHA-SIR-2016043242": ["S", 0.88, "PIPE_LINER"],
  "OSHA-SIR-2018054484": ["S", 0.72, "SUSPENDED_LOAD"],
  "OSHA-SIR-2016076909": ["S", 0.72, "RIG_FLOOR_PANEL"],
  "OSHA-SIR-2015010024": ["S", 0.90, "TIRE_ENERGY"],
  "OSHA-SIR-2020021385": ["S", 0.75, "BOP_TIP"],
  "OSHA-SIR-2018032710": ["S", 0.70, "DROPPED_LOAD"],
  "OSHA-SIR-2016065729": ["N", 0.93, "PINCH_LOCAL"],
  "OSHA-SIR-2020076617": ["S", 0.72, "GATE_ROLLER"],
  "OSHA-SIR-20171010045": ["S", 0.70, "HEAVY_DOOR"],
  "OSHA-SIR-20231211765": ["N", 0.99, "PINCH_LOCAL"],
  "OSHA-SIR-20201111093": ["S", 0.99, "VEHICLE_CRUSH"],
  "OSHA-SIR-2019054745": ["S", 0.94, "OUTRIGGER"],
  "OSHA-SIR-2015010444": ["S", 0.86, "VEHICLE_RUNOVER"],
  "OSHA-SIR-2018065466": ["N", 0.86, "ROLLING_LOCAL"],
  "OSHA-SIR-2015031093": ["S", 0.99, "CART_TIP"],
  "OSHA-SIR-20171212120": ["S", 0.70, "ROLLING_PIPE"],
  "OSHA-SIR-2017043386": ["N", 0.82, "ROLLING_LOCAL"],
  "OSHA-SIR-2019021931": ["S", 0.84, "ROLLING_PIPE"],
  "OSHA-SIR-2022098322": ["S", 0.98, "ROLLING_PIPE"],
  "OSHA-SIR-2021119791": ["S", 0.98, "LOAD_IN_CAB"],
  "OSHA-SIR-2018099398": ["S", 0.76, "UNRESTRAINED_CARGO"],
  "OSHA-SIR-2015118264": ["S", 0.88, "SUSPENDED_LOAD"],
  "OSHA-SIR-2015021264": ["S", 0.86, "SUSPENDED_LOAD"],
  "OSHA-SIR-2015010399": ["S", 0.99, "SUSPENDED_LOAD"],
  "OSHA-SIR-2015010670": ["S", 0.99, "TONG_SNAP"],
  "OSHA-SIR-2019077628": ["S", 0.80, "SUSPENDED_LOAD"],
  "OSHA-SIR-20161110668": ["S", 0.91, "PRESSURE_HOSE"],
  "OSHA-SIR-2015096308": ["N", 0.86, "PINCH_LOCAL"],
  "OSHA-SIR-2015020726": ["S", 0.92, "OUTRIGGER"],
  "OSHA-SIR-2016021254": ["S", 0.76, "TRENCHER_SWING"],
  "OSHA-SIR-2021032721": ["N", 0.98, "PINCH_LOCAL"],
  "OSHA-SIR-2019065947": ["S", 0.88, "SUSPENDED_LOAD"],
  "OSHA-SIR-2015052803": ["S", 0.99, "VEHICLE_RUNOVER"],
  "OSHA-SIR-20181212860": ["S", 0.99, "VEHICLE_OVERTURN"],
  "OSHA-SIR-2019054968": ["S", 0.90, "STRUCTURE_COLLAPSE"],
  "OSHA-SIR-2019065723": ["S", 0.99, "TORNADO"],
  "OSHA-SIR-2018076959": ["S", 0.99, "ELECTRIC_LINE"],
  "OSHA-SIR-2015118721": ["N", 0.96, "LOW_STEP"],
  "OSHA-SIR-2015053054": ["S", 0.90, "FIRE"],
  "OSHA-SIR-2022010682": ["S", 0.99, "CONFINED_FIRE"],
  "OSHA-SIR-20161010153": ["S", 0.97, "FIRE"],
  "OSHA-SIR-20251010643": ["S", 0.88, "MASS_STING"],
  "OSHA-SIR-2024032752": ["N", 0.91, "PINCH_LOCAL"],
};

const evidence = {
  BIO: ["Biological bite/sting; agent toxicity unspecified", "Employee was bitten", "No barrier information stated", "Potential severity cannot be established from the narrative", "The biting agent and credible severe consequence are not described well enough for a binary judgment."],
  ENTANGLE: ["Powered cable, winch, or spool", "Worker was caught or pulled by the line", "Line-of-fire and entanglement controls failed", "Whole-body draw-in or traumatic amputation", "The powered line could draw the worker further into equipment, creating credible fatal or life-altering exposure."],
  MACH_ENTANGLE: ["Moving belt, pulley, or machinery", "Worker contacted the operating mechanism", "Guarding or energy-isolation control was ineffective", "Draw-in, major amputation, or crushing", "Contact with an accessible moving mechanism could escalate beyond the hand to life-altering injury."],
  PINCH_LOCAL: ["Localized pinch or caught-between point", "Hand or finger was placed at the contact point", "Hand-positioning or pinch-point control failed", "Localized digit injury", "The described geometry confines exposure to a hand or finger without credible whole-body or fatal escalation."],
  ROLL_HEAVY: ["Uncontrolled rolling heavy component", "Worker handled the component in its roll path", "Chocking and stability control failed", "Crushing of a limb or body", "The heavy component was inadequately secured and could credibly crush more than the exposed hand."],
  CRUSH: ["Heavy moving object or equipment", "Worker was caught between fixed and moving objects", "Separation and line-of-fire controls failed", "Fatal or life-altering compression injury", "The worker occupied a full-body crush zone between heavy objects."],
  LIFT: ["Crane-handled heavy load", "Worker placed a hand at the load interface", "Hands-free positioning and line-of-fire controls failed", "Crushing by a shifting load", "The worker was directly exposed at a crane-handled load interface where load movement could cause serious crushing."],
  LIFT_CRUSH: ["Hoisted or lowered heavy component", "Worker was pinned against stationary material", "Load control and exclusion-zone controls failed", "Fatal or life-altering crushing", "Loss of control of the hoisted component placed the worker in a full-body crush zone."],
  LADDER_TOOL: ["Hydraulic tool and work from ladder", "Worker's hand was struck while on the ladder", "Tool-control and fall-protection context is incomplete", "Serious hand injury or fall; severity unclear", "The narrative does not establish ladder height or whether tool movement could credibly produce a SIF consequence."],
  HIGH_RIG: ["Moving rig blocks, pipe, or retained line at elevation", "Worker was in the movement path on the rig", "Coordination, retention, or exclusion controls failed", "Fall, crushing, or major amputation", "Rig movement exposed the worker to high-energy equipment with credible fatal or life-altering consequences."],
  LOW_STEP: ["Low step and ankle roll", "Worker stepped down six inches", "No critical-control failure described", "Ordinary musculoskeletal injury", "A six-inch step and ankle roll do not establish credible fatal or life-altering potential."],
  EXCAVATION: ["Excavation wall collapse", "Worker was inside a 12-foot excavation", "Cave-in protection failed or was absent", "Burial, crushing, or asphyxiation", "A worker inside the deep excavation was directly exposed to a potentially fatal cave-in."],
  VEHICLE_LOCAL: ["Moving forklift with external contact", "Operator's foot caught on a stationary tote", "Clearance control was inadequate", "Localized lower-limb injury", "The described event is a localized foot twist without evidence of run-over, collision, or whole-body crush exposure."],
  DROPPED_OBJECT_LINE: ["Falling top drive and retracting drill line", "Worker was struck in the line's recoil path", "Equipment securement and line-of-fire controls failed", "Fatal strike, crushing, or neck trauma", "A heavy component fell 30 feet and retracted a line through the occupied work area."],
  HOT_LINE: ["Boiler condensate line and possible heat", "Worker's hand was pinched and burned", "Line condition and isolation details are incomplete", "Thermal or pressure injury; extent unclear", "Temperature, pressure, and release exposure are too unclear to establish credible SIF potential."],
  FIRE: ["Flame or flash-fire event", "Worker was engulfed across the upper body", "Fuel isolation or ignition control failed", "Fatal burns or airway injury", "A flame event engulfed the worker's face and torso, creating credible fatal burn and inhalation exposure."],
  HOT_SLURRY: ["640°F process slurry", "Workers opened process piping and were sprayed", "Isolation and valve integrity failed", "Fatal burns or extensive permanent injury", "Release of extremely hot slurry onto exposed workers created credible fatal or life-altering thermal injury."],
  SAME_FALL: ["Same-level loss of balance or slip", "Worker fell on the same level", "Ordinary footing control failed", "Injury from a ground-level fall", "The narrative describes an ordinary same-level fall without an independent high-energy or elevated exposure."],
  ELECTRIC_ARC: ["High-voltage electrical arc flash", "Worker was at energized equipment", "Electrical isolation or arc-flash controls failed", "Electrocution or fatal burns", "The worker was directly exposed to high-voltage arc energy with credible fatal consequences."],
  ELECTRIC_SHOCK: ["Unexpected electrical energy", "Worker contacted or tested electrical equipment", "De-energization or electrical protection was ineffective", "Electrocution or cardiac injury", "Direct electrical exposure during equipment work could credibly be fatal even though the reported injury was limited."],
  WINCH_HAND: ["Winch line and bridle entanglement", "Worker's finger was wrapped by the line", "Hand placement near the line was uncontrolled", "Digit injury; wider draw-in potential unclear", "The narrative does not establish whether the line was powered or capable of drawing the worker beyond the finger."],
  EXPLOSION: ["Flammable gas explosion or flash fire", "Worker was within the blast and flame area", "Leak detection, containment, or ignition control failed", "Fatal blast, burns, or structural injury", "Accumulated or leaking gas ignited around personnel, creating credible fatal blast and burn exposure."],
  PRESSURE: ["High-pressure pipe or vessel failure", "Worker was in the projectile and release path", "Pressure containment or test controls failed", "Fatal projectile or blunt-force trauma", "The pressurized component failed and launched material through an occupied work area."],
  CHEM_PRESSURE: ["Pressurized caustic chemical release", "Chemical bypassed the face shield and struck face/neck", "Depressurization and face protection were ineffective", "Blindness, airway injury, or extensive burns", "Pressurized caustic reached the worker's face and neck, creating credible life-altering chemical injury."],
  COLD: ["Environmental cold exposure", "Worker's fingers developed frostbite", "Exposure duration and controls are not described", "Permanent tissue injury is possible but not established", "The narrative lacks temperature, duration, and frostbite severity needed for a binary potential judgment."],
  HEAT: ["Environmental heat during field work", "Worker developed heat-illness symptoms after exposure", "Heat-stress controls are not described", "Heat stroke and death", "Field heat exposure produced illness symptoms and could credibly progress to fatal heat stroke."],
  HAND_LOAD: ["Hand-carried tool or component", "Dropped item landed on the worker's hand", "Manual-handling control failed", "Localized hand injury", "The carried item struck only the hand and no credible fatal or whole-body escalation is described."],
  STRUCK_UNKNOWN: ["Falling display items after a same-level fall", "Items struck the worker's head", "Item mass and height are unspecified", "Head injury severity cannot be established", "The report omits the item mass and fall height needed to judge credible SIF energy."],
  FALL_HIGH: ["Elevated fall greater than about six feet", "Worker fell from elevated equipment or structure", "Fall prevention or personal fall protection failed", "Fatal head trauma or permanent spinal injury", "The described fall height and failed fall control create credible fatal or life-altering potential."],
  FALL_LOW: ["Low-level fall", "Worker fell less than about six feet", "Footing or access control failed", "Ordinary fall injury without established SIF energy", "The low fall height and described geometry do not establish credible fatal or life-altering potential."],
  TRENCH_EDGE: ["Collapse at a deep trench edge", "Worker fell into and was partly buried by a 12-foot trench", "Setback and cave-in protection failed", "Fatal burial, crushing, or fall trauma", "Collapse of the deep trench edge exposed the worker to both a serious fall and potential burial."],
  PRESSURE_FALL: ["Pressurized hose reaction and elevated platform", "Hose force threw the worker from the platform", "Hose control and elevated-work controls failed", "Head trauma or serious fall injury", "Uncontrolled hose force ejected the worker from an elevated platform, creating credible severe head-injury potential."],
  TOXIC_FALL: ["Anhydrous ammonia exposure while on ladder", "Eye irritation impaired the worker during descent", "Chemical containment and safe egress controls failed", "Toxic inhalation, blindness, or serious fall", "Ammonia exposure impaired vision while the worker was on a ladder, combining toxic and fall hazards."],
  SMALL_FIRE: ["Ignited gasoline during fueling", "Worker was next to the burning fuel", "Fuel-transfer and ignition controls failed", "Escalating burns or clothing ignition", "Gasoline ignited during transfer with the worker in immediate proximity, allowing credible life-altering burn escalation."],
  CLOTHING_FIRE: ["Welding slag ignited clothing", "Worker's upper-body clothing burned while on a ladder", "Hot-work shielding and clothing controls failed", "Fatal burns or fall from ladder", "Burning clothing on an elevated worker could rapidly cause extensive burns or a serious fall."],
  ELECTRIC_LINE: ["Contact with overhead high-voltage line", "Workers were on or near conductive equipment when contact occurred", "Overhead-line clearance control failed", "Electrocution or fatal arc injury", "Equipment contacted a high-voltage line while personnel were exposed to the energized system."],
  TOXIC_INGEST: ["Diesel fuel ingestion", "Fuel entered the worker's mouth", "Transfer containment failed", "Aspiration or systemic harm; dose unknown", "The swallowed quantity and aspiration evidence are missing, so credible SIF severity cannot be established."],
  TOXIC_GAS: ["Acute H2S or ammonia atmosphere", "Workers inhaled toxic gas and developed severe symptoms", "Gas containment, detection, or respiratory protection failed", "Fatal poisoning or permanent respiratory injury", "Personnel were directly exposed to a toxic gas cloud capable of fatal inhalation injury."],
  MANUAL_CUT: ["Hand utility knife", "Knife cut the user's fingertip", "Cutting technique and hand protection failed", "Localized hand injury", "The manual cutting event is confined to the fingertip without credible fatal or whole-body escalation."],
  ROTATING_IMPROPER: ["Operating well pulley and improvised wrench braking", "Worker placed a hand-held wrench at the moving mechanism", "Energy isolation and proper operating method failed", "Entanglement, struck-by injury, or major amputation", "Using a wrench against an operating pulley exposed the worker to uncontrolled rotating energy."],
  STORED_ENERGY_BAR: ["Unexpected stored air pressure and engine movement", "A lever bar was driven into the worker's arm", "Stored-energy release was not controlled", "Fatal blunt-force strike or crushing", "Stored pressure unexpectedly rotated the engine and propelled a bar through the occupied work area."],
  TORQUE_RECOIL: ["Released downhole torque in a rod string", "A large pipe wrench spun into the worker", "Stored-torque control and exclusion failed", "Fatal head or torso strike", "Unexpected torque return accelerated a large wrench with enough energy for a fatal strike."],
  WINCH_SCAFFOLD: ["Suddenly tensioned winch line and long bar", "Worker on a scaffold was at the bar's pinch and movement path", "Winch coordination and line-of-fire controls failed", "Fall, crushing, or major hand injury", "A taut winch line drove a long bar beside an elevated worker, creating credible fall and struck-by escalation."],
  GRATE_CRUSH: ["Moving floor grate", "Worker's lower leg was pinned against equipment", "Communication and push-stop controls failed", "Crush severity depends on grate mass and travel", "The report does not establish enough load energy or body exposure to resolve whether SIF-level crushing was credible."],
  EXPLOSIVES: ["Premature explosive detonation", "Workers were within the blast area", "Explosive timing and initiation controls failed", "Fatal blast or fragmentation injury", "An explosive detonated prematurely with multiple workers onsite, creating obvious fatal blast potential."],
  VEHICLE_COLLISION: ["Powered vehicle collision", "Occupants were in the impact path", "Traffic separation and visibility controls failed", "Fatal impact, crushing, or impalement", "The moving vehicle collision involved heavy equipment or protruding steel with credible fatal impact energy."],
  VEHICLE_EJECTION: ["Unbalanced aerial lift during loading", "Operator was ejected from the basket", "Load stability and restraint controls failed", "Fatal fall or crushing by equipment", "Loss of lift stability ejected the operator and could credibly cause fatal fall or crush injury."],
  VEHICLE_OVERTURN: ["Off-road vehicle rollover or loss of control", "Operator occupied the overturning or departing vehicle", "Vehicle stability or route controls failed", "Fatal crush or ejection", "Loss of vehicle stability exposed the occupant to credible fatal rollover or ejection consequences."],
  FALL_UNKNOWN: ["Fall from an earthen berm", "Worker fell from an unspecified height", "Edge and footing controls are not described", "Potential severity depends on missing height and surface details", "The berm height and fall geometry are missing, preventing a defensible binary judgment."],
  OVEREXERTION: ["Manual movement of a toolbox", "Worker experienced exertion while moving it", "Ergonomic control was inadequate", "Musculoskeletal injury", "Ordinary manual overexertion does not establish credible fatal or life-altering energy."],
  VEHICLE_RUNOVER: ["Heavy mobile equipment run-over", "Pedestrian's limb was under the moving equipment", "Pedestrian separation and spotter controls failed", "Fatal whole-body run-over or crushing", "A pedestrian was in the travel path of heavy equipment that could continue over the body."],
  VEHICLE_CRUSH: ["Vehicle backing or movement between equipment", "Worker was caught between large vehicles or trailer", "Spotting and exclusion-zone controls failed", "Fatal compression injury", "The worker occupied a full-body pinch zone between powered vehicles and fixed equipment."],
  DROPPED_LOAD: ["Pipe rack fell from forklift forks", "Worker was beside and partly under the falling rack", "Load securement and exclusion-zone controls failed", "Fatal struck-by or crushing injury", "A heavy rack fell from lifting equipment into an occupied area and could have struck the body."],
  STAIRS_LOW: ["Short stair descent", "Worker fell on the third step", "Ordinary access control failed", "Localized fall injury", "A short stair fall without an added high-energy hazard does not establish credible SIF potential."],
  STRUCK_LOW: ["Contact with a fixed staircase", "Worker bumped a leg against the structure", "Clearance awareness was inadequate", "Minor localized impact", "Low-energy contact with a stationary staircase has no credible SIF escalation in the narrative."],
  EYE_IMPALE: ["Protruding threaded rod at eye level", "Worker's eyelid contacted the rod", "Protrusion guarding and clearance controls failed", "Permanent eye loss or penetrating head injury", "The unguarded rod contacted the eye area and could credibly cause permanent vision loss."],
  ENERGY_PROJECTILE: ["Rapid energy release and propelled object", "Worker was struck in the head", "Isolation and depressurization controls failed", "Fatal cranial trauma", "Opening the lift released energy and propelled an object toward the worker's head."],
  DROPPED_OBJECT_LOCAL: ["Small component dropped at hand level", "Worker's hand or finger was beneath the component", "Hand placement and support control failed", "Localized digit injury", "The described drop is confined to the hand without credible full-body or fatal exposure."],
  STORED_TENSION: ["Forklift-tensioned pipe connection", "Worker held the regulator beside the separating pipe", "Tension release and exclusion-zone controls failed", "Fatal projectile or whipping-pipe strike", "The pipe separated while under powered tension and could credibly strike the worker's head or body."],
  PIPE_SWING: ["Backhoe-tensioned fence rail", "Worker sat in the rail's swing and fall path", "Stored-tension and exclusion controls failed", "Fatal penetrating or head injury", "The released rail flipped upright and fell toward the occupied operator seat."],
  DOOR_HEAD: ["Wind-driven engine-room door", "Door struck the worker's head", "Door securement failed", "Potential head injury; door energy unclear", "The door mass and closing travel are not described well enough to resolve SIF-level head-impact potential."],
  RIG_COLLAPSE: ["Drill-rig tower movement during teardown", "Worker was in the tower's fall path", "Structural-control and exclusion-zone controls failed", "Fatal crushing or spinal injury", "The rig tower came down into an occupied area, creating credible fatal crushing exposure."],
  FALLING_UNKNOWN: ["Falling material of unspecified mass or height", "Material struck a worker", "Support or containment failed", "Severity depends on missing energy and geometry", "The report lacks enough mass, fall-height, and body-position detail for a defensible binary judgment."],
  CRANE_FALL: ["Free-falling crane headache ball and fast line", "Worker was beneath the boom and struck in head and body", "Suspended-load exclusion and hoist control failed", "Fatal blunt-force or crushing injury", "A heavy crane component free-fell onto a worker beneath the boom."],
  TIPPING_EQUIP: ["Heavy equipment tipping into occupied area", "Worker was beside and struck by the falling boom", "Ground stability and exclusion-zone controls failed", "Fatal crushing by overturning equipment", "Loss of ground or excavation stability caused heavy equipment to tip toward personnel."],
  DROPPED_HEAVY: ["Unsupported 450-pound flange", "Worker's hand was between the flange and rack", "Dunnage and stability controls failed", "Crushing of a limb or body", "Failure of support for a 450-pound flange created a credible heavy-load crush exposure."],
  LINE_WHIP: ["Large line whipping during pigging", "Worker was in the line's movement path", "Line restraint and energy-control measures failed", "Fatal head strike or whole-body trauma", "The 12-inch line whipped through the occupied area with sufficient energy for a fatal strike."],
  WEDGE_PROJECTILE: ["Metal wedge expelled during flange spreading", "Worker's face was in the projectile path", "Tool retention and face-position controls failed", "Blindness or fatal head injury", "A struck metal wedge was ejected toward the face with credible life-altering projectile energy."],
  PLATE_ROLL: ["Rolling heavy steel plate", "Worker stood beside the plate and pipe", "Plate stability and line-of-fire controls failed", "Crushing of a limb or body", "The heavy steel plate rolled unexpectedly in the worker's occupied area and could cause major crushing."],
  VALVE_HAND: ["Manually actuated valve pinch", "Worker's hand was inside the valve movement point", "Hand-positioning control failed", "Localized hand injury", "The narrative confines movement and exposure to the hand without credible whole-body escalation."],
  MACHINE_RESTART: ["Unexpected machine activation during entry", "A worker remained inside and was pinned", "Lockout, communication, and personnel-clearance controls failed", "Fatal crushing or major amputation", "The machine was restarted with a worker inside its danger zone."],
  ROTATING_HAND: ["Manual engine rotation with Allen wrench", "Worker's hand was at the wrench and engine interface", "Energy control and proper starting method failed", "Hand injury; wider entanglement potential unclear", "The report does not establish enough rotation speed or body exposure to resolve SIF potential beyond the hand."],
  DRILL_PIPE_BOW: ["Powered drill movement and bowed pipe", "Worker was in the pipe's release path", "Alignment and stop-work controls failed", "Fatal head or torso strike", "Continued powered movement bowed the casing and released it toward the worker's face."],
  COUNTERWEIGHT: ["Rotating pump-jack counterweight", "Worker occupied the counterweight's sweep path", "Mechanical restraint and exclusion controls failed", "Fatal crushing or spinal trauma", "A large counterweight rotated into the worker's back with credible fatal mechanical energy."],
  POWER_SWIVEL: ["Unintended power-swivel activation and swinging wrench", "Worker stood in the wrench sweep path", "Control-panel securement and energy isolation failed", "Fatal head or torso strike", "Unexpected activation accelerated a 48-inch wrench through an occupied work area."],
  POWER_TONGS: ["Unexpectedly energized power tongs", "Worker's hand was inside during component change", "Energy isolation failed", "Crushing or draw-in beyond the hand", "Power tongs energized during maintenance, creating credible uncontrolled mechanical entrapment."],
  SWING_RADIUS: ["Drilling-equipment swing radius", "Worker was struck and pinned against a cage", "Barricade coverage and personnel separation failed", "Fatal crushing", "The rotating equipment entered an occupied zone and pinned the worker against a fixed structure."],
  SUSPENDED_LOAD: ["Suspended or forklift-supported heavy load", "Worker was beside the shifting or swinging load", "Load control and exclusion-zone controls failed", "Fatal struck-by or crushing injury", "The worker was within the movement zone of a lifted heavy object that shifted or swung unexpectedly."],
  CRANE_FIRE: ["Crane instability, falling load, ruptured well piping, and fire", "Workers were in the collapse and fire area", "Ground-bearing, lifting, and process-isolation controls failed", "Fatal crushing, explosion, or burns", "Crane ground failure caused load swing, wellhead damage, collapse, and fire around exposed workers."],
  VENOMOUS_BITE: ["Rattlesnake venom", "Worker was bitten while handling stored tires", "Animal inspection or exclusion control failed", "Fatal envenomation or permanent tissue injury", "A confirmed rattlesnake bite creates credible fatal envenomation even without relying on the reported outcome."],
  STEAM_AVOID: ["Low-pressure steam vent and falling water", "Worker moved away and struck a pipe", "Vent condition and path clearance were inadequate", "Thermal severity is unclear; impact was low energy", "Water temperature and vent-release energy are missing, so the SIF potential cannot be resolved."],
  WALKING: ["Level-ground walking", "Worker was walking without another incident", "No critical barrier failure described", "Ordinary musculoskeletal injury", "Level walking without an external hazardous-energy event does not establish credible SIF potential."],
  ANIMAL_FORCE: ["Uncontrolled horse movement", "Worker was in the pen as the horse hit railing", "Animal-control and separation controls failed", "Crushing, trampling, or fatal impact", "A large uncontrolled animal could credibly crush or trample the exposed worker."],
  RIGGING_HAND: ["Come-along swivel failure during ram replacement", "Worker's thumb was at the rigging interface", "Rigging component integrity failed", "Wider load movement is possible but not described", "The failed swivel suggests stored load energy, but load size and body exposure are insufficient for a binary judgment."],
  TREE_CRUSH: ["Moving or falling trees", "Worker was pinned between two trees", "Tree-control and exclusion-zone controls failed", "Fatal whole-body crushing", "The worker occupied a full-body pinch zone between large trees during clearing."],
  SUPPORTED_LOAD: ["Forklift-supported cutting trough and removable support", "Worker's hand was under the support during release", "Load support and hand-clearance controls failed", "Collapse or crushing by the trough", "Removing a support while a forklift held the trough created credible load-collapse exposure."],
  POWER_TONGS_HAND: ["Tong plate and securing pin", "Worker's hand was caught between components", "Equipment state and isolation are not stated", "Permanent hand injury; wider draw-in unclear", "The report lacks enough information about tong movement and energy to resolve SIF potential beyond the hand."],
  HIGH_RIG_HAND: ["Powered tongs and elevated derrick work", "Worker's hand was struck while stabbing pipe", "Equipment coordination failed", "Hand injury or fall; exposure extent unclear", "The narrative does not establish whether the elevated worker faced a credible fall or whole-body equipment hazard."],
  RIG_SECTION: ["Moving derrick mast sections", "Worker was beside the closing mast interface", "Personnel-clearance and mast-movement controls failed", "Fatal crushing or major amputation", "Movement of large derrick sections created a crush zone that could capture more than the worker's hand."],
  MACHINE_CRUSH: ["Powered hydraulic gate", "Worker was caught in the gate", "Guarding and energy control failed", "Fatal or life-altering crushing", "The worker was caught by a powered gate with sufficient travel to crush the lower body."],
  EXCAVATION_STEP: ["Entry into an excavation", "Worker was stepping down when injured", "Excavation depth and access controls are not stated", "Potential fall severity depends on missing depth", "The excavation depth and fall mechanism are too vague for a defensible binary judgment."],
  HIGHWAY_COLLISION: ["65-mph roadway collision", "Worker occupied the struck barricade vehicle", "Traffic-control protection failed", "Fatal impact or aortic injury", "A high-speed vehicle struck the worker's stationary truck with obvious fatal collision energy."],
  BOAT_COLLISION: ["Boat impact and occupant ejection", "Worker was thrown from the seat during pipeline inspection", "Navigation and occupant-restraint controls failed", "Fatal impact or drowning", "A vessel collision ejected the worker and could credibly cause fatal impact or overboard exposure."],
  CHAIN_TENSION: ["Loader-controlled lifting chain", "Worker's hand was at the chain and bin interface", "Unexpected control activation tightened the chain", "Digit injury; whole-body line-of-fire exposure unclear", "The chain tightened unexpectedly, but the narrative confines the known exposure to a finger and omits wider load movement."],
  BUTANE_RELEASE: ["Liquid butane release", "Worker was sprayed while changing hoses", "Isolation and containment failed", "Cryogenic injury, fire, or vapor asphyxiation", "Direct butane release around a worker creates credible life-altering cold and flammable-vapor hazards."],
  HOT_ASPHALT: ["Pressurized 400°F asphalt", "Spray reached face, head, neck, chest, and arms", "Pressure containment and splash protection failed", "Fatal burns, airway injury, or blindness", "Pressurized hot asphalt struck the worker's upper body and face with credible fatal burn potential."],
  STEAM_RELEASE: ["Undepressurized furnace steam/condensate line", "Worker disconnected the live hose at the furnace", "Isolation and depressurization failed", "Fatal burns or airway injury", "Disconnecting an undepressurized hot line exposed the worker's face and torso to steam."],
  RING_CATCH: ["Ring snag on fixed structure", "Worker's ring finger caught during a reach or fall", "Jewelry and snag-hazard control failed", "Localized degloving or digit injury", "The snag mechanism is confined to the ring finger without credible fatal or whole-body escalation."],
  MACHINE_VAGUE: ["Mulch machine", "Worker's finger contacted the machine", "Guarding and operating details are missing", "Potential extent of machine entanglement is unclear", "The report does not describe the contact geometry or whether the machine could draw in more than a finger."],
  TOOL_VAGUE: ["Setting tool during teardown", "Worker's fingertip was injured", "Energy state and failure mechanism are missing", "Potential severity cannot be established", "The report is too vague about tool energy and exposure to support a binary SIF judgment."],
  ENGULFMENT: ["Collapsing adsorbent inside a tower", "Worker was inside and engulfed", "Material-stability and confined-space controls failed", "Fatal asphyxiation or crushing", "Material detached inside the tower and engulfed the worker, creating obvious fatal asphyxiation potential."],
  ENTANGLE_FALL: ["Jerking tugger line at the drill floor", "Worker held the line and was pulled over a safety gate", "Line handling and fall-prevention controls failed", "Fatal fall, entanglement, or spinal injury", "The powered line pulled the worker from the drill floor and over a barrier."],
  CHEM_EXPLOSION: ["Reactive chemical explosion", "Worker was beside the H2S tower during cleaning", "Chemical compatibility and process controls failed", "Fatal blast, fire, or toxic exposure", "A chemical explosion occurred during tower cleaning with the worker in the blast area."],
  TANK_EXPLOSION: ["Process or storage tank explosion", "Workers were on or at the opened tank", "Gas-freeing, ignition, and vessel-entry controls failed", "Fatal blast, fall, or extensive burns", "The tank exploded while workers were on or cleaning it, creating multiple credible fatal mechanisms."],
  ENV_CONTACT: ["Mud and water contact", "Worker stepped into knee-deep mud/water", "No specific critical-control failure stated", "Infection risk without established SIF energy", "Environmental contact alone does not establish credible fatal or life-altering potential in the narrative."],
  MUD_PRESSURE_EYE: ["Pressurized oil-based drilling mud", "Release blew off eye protection and entered workers' eyes", "Depressurization and eye protection failed", "Permanent blindness or serious chemical injury", "Pressurized mud defeated PPE and directly exposed multiple workers' eyes."],
  CHEM_UNKNOWN: ["Unknown or unspecified chemical exposure", "Chemical contacted the worker", "Containment failed but material properties are missing", "Potential severity cannot be established", "Chemical identity, concentration, and exposure extent are too incomplete for a binary judgment."],
  BURN_UNKNOWN: ["Unspecified hot or chemical release", "Worker was burned across lower torso and legs", "Maintenance isolation details are absent", "Burn severity could be serious but energy source is unclear", "The report omits the substance, temperature, and release mechanism needed to establish SIF potential."],
  COLLAPSE_UNKNOWN: ["Unexplained loss of consciousness during fuel unloading", "Worker collapsed near transfer operations", "Cause and exposure pathway are unknown", "Medical or toxic consequence cannot be attributed", "The narrative does not establish whether hazardous exposure, illness, or another cause produced the collapse."],
  HF_RELEASE: ["Hydrogen fluoride release", "Workers were near the leaking alkylation piping", "Process containment and emergency protection failed", "Fatal toxicity or extensive corrosive burns", "Hydrogen fluoride escaped near personnel and can cause fatal systemic and respiratory injury."],
  STAIR_COLLAPSE: ["Detached access stairs and six-foot fall", "Worker fell and was struck by the stairs", "Temporary access securement failed", "Head trauma or crushing by stairs", "The access structure detached, combining a borderline-height fall with a heavy falling object."],
  PLATFORM_COLLAPSE: ["Collapse of catwalk or equipment stand", "Workers were on or beside the failing structure", "Structural support and inspection controls failed", "Fatal fall or crushing", "The work platform collapsed with personnel on and beside it, creating credible fall and crush exposure."],
  RIG_PIPE_CRUSH: ["Moving drill-pipe stand and top drive", "Fallen worker's hand was in the pipe placement zone", "Coordination and line-of-fire controls failed", "Crushing by a heavy pipe stand", "A powered rig operation set a heavy pipe stand into the occupied deck area."],
  HEAVY_HEAD_STRIKE: ["Falling railroad tie", "Heavy tie landed on the worker's head", "Manual-load and drop-zone controls failed", "Fatal cranial trauma", "A heavy railroad tie fell onto the head and could credibly be fatal."],
  DUMP_BOX: ["Lowering dump box", "Worker fell into the box's pinch zone", "Personnel-clearance and lowering controls failed", "Fatal crushing by the descending box", "A descending dump box created a crush zone that could capture more than the worker's hand."],
  SHARP_PROTRUSION: ["Unguarded sharp steel protrusion", "Worker fell onto the protruding metal", "Protrusion guarding and housekeeping controls failed", "Fatal impalement or permanent organ injury", "The fall path contained an exposed sharp steel projection capable of penetrating the torso or head."],
  HOT_COKE: ["Hot petroleum coke and possible steam", "Worker fell into the hot material", "Thermal-area separation and footing controls failed", "Extensive burns or fatal thermal injury", "Falling into hot coke and steam created credible life-altering thermal exposure beyond an ordinary trip."],
  WATERJET: ["40,000-psi water jet", "Worker's arm crossed the active jet", "Jet isolation and access controls failed", "Fatal bleeding or traumatic amputation", "An active ultra-high-pressure water stream can sever tissue and major vessels."],
  LINE_SNAP_FALL: ["Tensioned rig line snapback", "Elevated worker was struck or pulled away from support", "Line condition, separation, and fall controls failed", "Fatal fall or snapback trauma", "Tensioned line movement displaced an elevated worker and could cause fatal impact or fall."],
  HOT_PIT: ["Hot water and steam condensate in ground opening", "Worker fell into the hot liquid", "Opening protection and thermal isolation failed", "Severe burns or steam injury", "Even a shallow fall placed both legs into hot water and steam capable of extensive burns."],
  OPEN_CELLAR: ["Unguarded well-cellar opening beside moving BOP work", "Spotter stepped backward into the opening", "Temporary guard and safe-position controls failed", "Head trauma, fall injury, or interaction with moving equipment", "The open cellar was immediately beside truck-pulled heavy equipment and the spotter's work position."],
  HOLE_UNKNOWN: ["Unspecified ground opening", "Worker stepped into the hole", "Opening marking or protection failed", "Potential severity depends on missing depth", "The hole depth and fall geometry are not stated, preventing a defensible binary judgment."],
  RAIL_COLLISION: ["Uncontrolled loaded railcars", "Impact knocked a worker from the car string", "Railcar securement and personnel-clearance controls failed", "Fatal collision, crushing, or fall", "Released loaded railcars collided with another string while a worker was exposed on the cars."],
  UNSTABLE_SKIDS: ["Shifted stacked skids on pipeline", "Worker stood on the skids beside pipe hardware", "Work-platform stability and footing controls failed", "Fall or crushing by pipe/flange", "An improvised elevated support shifted under the worker during pipeline work."],
  CONFINED_FIRE: ["Flash fire inside a vessel", "Worker was within the vessel during hot work", "Gas-freeing, ventilation, and hot-work controls failed", "Fatal burns, smoke inhalation, or entrapment", "A flash fire occurred inside a vessel around the worker, creating fatal burn and egress hazards."],
  FIRE_FALL: ["Grass fire beside a ravine", "Worker was near the fire and fell 6–8 feet", "Vehicle recovery, ignition, and terrain controls failed", "Burns plus serious fall trauma", "The fire event drove or coincided with a fall into a ravine, creating combined SIF mechanisms."],
  ASSAULT: ["Physical altercation", "Worker was struck by another person", "Violence controls failed", "Severity depends on force, weapons, and continued assault", "The report lacks enough detail about the assault mechanism to resolve credible fatal potential."],
  PRESSURE_FIRE: ["Pressurized hydrocarbon leak followed by fire", "Workers were drenched in released liquid and gas", "Pressure containment, isolation, and ignition controls failed", "Fatal burns or explosion", "A pressurized release soaked personnel and then ignited around them."],
  POISON_INGEST: ["Antifreeze in a mislabeled drink container", "Worker ingested the toxic liquid", "Container labeling and chemical-storage controls failed", "Fatal systemic poisoning", "A toxic chemical was consumed as a beverage because it was stored in an improperly labeled container."],
  INHALATION_VAGUE: ["Unspecified inhalation hazard", "Worker was reportedly exposed", "Material and control details are absent", "Potential severity cannot be established", "The report identifies no substance, concentration, duration, or symptoms beyond hospitalization."],
  LONG_ROD_RECOIL: ["Wave recoil through a 25-foot sucker rod", "Worker held the far end as it whipped upward", "Coordinated handling and exclusion controls failed", "Fatal head or face strike", "The long rod transferred impact energy and whipped toward the worker's head."],
  HAMMER_HAND: ["Hand-held sledge or hammer", "Worker's hand was near the intended strike point", "Hand-positioning and coordination controls failed", "Localized hand injury", "The striking geometry is confined to the hand and does not establish credible SIF escalation."],
  GLASS_HAND: ["Broken light globe", "Glass cut the worker's fingertip", "Glass-handling protection failed", "Localized laceration", "The broken-glass event is confined to a fingertip without credible life-threatening exposure."],
  HAND_TOOL_BREAK: ["Broken chain wrench", "Broken tool struck the user's hand", "Tool condition failed", "Localized hand and wrist injury", "The broken hand tool struck the hand with no credible head, torso, or whole-body exposure described."],
  WRENCH_HAND: ["Fast-moving drill-fork or wrench", "Worker's hand was struck", "Tool speed and body exposure are not described", "Potential extent beyond hand is unclear", "The report lacks enough energy and trajectory detail to decide whether SIF-level struck-by exposure existed."],
  BIO_MINOR: ["Brush-wire puncture with later infection", "Worker's arm was exposed", "Wound prevention failed", "Infection severity is not a high-energy precursor", "A minor puncture and subsequent infection do not establish credible SIF potential from the described event."],
  HIGHWAY_ROLLOVER: ["Road vehicle rollover", "Driver occupied the overturning heavy vehicle", "Vehicle control or roadway margin failed", "Fatal ejection or crushing", "A road-going heavy vehicle rolled over with its driver exposed to fatal impact and crush energy."],
  MOORING_SNAPBACK: ["Parted ship line under tension", "Worker was in the line's snapback path", "Line integrity and snapback-zone controls failed", "Fatal strike or traumatic amputation", "A loaded ship line broke and recoiled through an occupied dock area."],
  REPORT_VAGUE: ["Unspecified incident mechanism", "An injury is reported without exposure detail", "Barrier information is absent", "Potential consequence cannot be inferred", "The narrative is too incomplete to determine hazard energy, exposure, or credible SIF consequence."],
  VEHICLE_VAGUE: ["Motorized vehicle incident with limited detail", "Worker occupied or drove the vehicle", "Speed, collision geometry, and restraints are unstated", "Potential impact severity cannot be established", "The vehicle involvement alone is insufficient without speed, rollover, collision, or ejection details."],
  DROPPED_LOAD_FALL: ["Dropped valve from crane rigging striking manlift", "Workers were knocked from the lift", "Rigging, load securement, and fall controls failed", "Fatal struck-by or elevated fall", "A valve fell 14 feet onto the occupied manlift and ejected workers to the ground."],
  DERRICK_FALL: ["Fall while descending a workover-rig derrick", "Worker was on the derrick ladder", "Fall protection or climbing controls failed", "Fatal fall or permanent spinal injury", "A fall from a derrick ladder carries credible SIF potential even though the exact distance is omitted."],
  RACK_COLLAPSE: ["Unstable heavy rack on jack stands", "Worker was on top as the rack fell", "Leveling and support controls failed", "Crushing or fall onto surrounding material", "The unstable rack fell while supporting a worker, creating combined crush and fall exposure."],
  DRILL_REAMER: ["Operating drill reamer in an open hole", "Worker fell into the hole and contacted the reamer", "Access protection and equipment exclusion failed", "Fatal entanglement or traumatic amputation", "The worker entered the active reamer zone and could be drawn into rotating equipment."],
  PRESSURE_ESCAPE: ["Hissing pressure during pipe breakout", "Worker escaped by jumping from the rig floor", "Pressure control and safe egress were inadequate", "Pressure release plus serious fall", "Evidence of uncontrolled pressure forced an elevated worker to jump from the rig floor."],
  TRAIN_ESCAPE: ["Disabled manlift over live railroad tracks", "Worker was trapped in the bucket as a train approached", "Equipment reliability and rail-crossing controls failed", "Fatal train collision or emergency fall", "The worker had to jump from an elevated lift to avoid an approaching train."],
  STRUCTURE_FIRE: ["Occupied guard-shack fire", "Workers were inside when the fire began", "Fire prevention and emergency response controls failed", "Fatal burns or smoke inhalation", "A sudden fire in a small occupied structure created credible burn and inhalation hazards."],
  ROAD_PEDESTRIAN: ["Road vehicle striking a pedestrian", "Worker was on foot in the vehicle path", "Traffic separation and driver-control measures failed", "Fatal blunt-force trauma", "A pedestrian was directly exposed to roadway vehicle impact energy."],
  RAIL_CRUSH: ["Railcars closing together", "Worker was caught between the cars", "Rail movement and personnel-clearance controls failed", "Fatal whole-body crushing", "The worker occupied the coupling zone between moving railcars."],
  LONG_PIPE_LOAD: ["125-foot pipe carried by multiple vehicles", "Worker guided the swaying pipe beside a building", "Load control and hands-free guidance failed", "Fatal crushing by the long heavy load", "The long pipe swayed into a fixed structure with the worker at the load interface."],
  TRAILER_ROLLOVER: ["Jack-knifing trailer rollover", "Spotter stood beside the trailer as it overturned", "Vehicle movement and spotter separation failed", "Fatal crushing", "The trailer rolled onto the exposed spotter."],
  GOLF_CART_PIN: ["Unintended golf-cart acceleration", "Worker was pushed against a skid plate", "Cargo securement and accelerator protection failed", "Potential crush severity is unclear", "The report does not establish cart speed or whether the pinning geometry could credibly become fatal."],
  LOADER_PULL: ["Loader pulled a connected object onto worker", "Worker was at the chain and load interface", "Communication and loader separation controls failed", "Fatal crushing by the shifting load", "Powered loader movement dragged the connected object onto the worker's legs and could involve the body."],
  SMALL_VEHICLE_COLLISION: ["Go-cart collision with parked car", "Driver occupied the go-cart", "Speed and restraint details are missing", "Potential impact severity cannot be established", "The small-vehicle collision lacks speed and geometry needed for a defensible SIF determination."],
  FIREARM: ["Unintentional firearm discharge", "Worker's body was in the bullet path", "Firearm storage and handling controls failed", "Fatal gunshot wound", "An uncontrolled firearm discharge has inherent credible fatal potential regardless of strike location."],
  FIREARM_ASSAULT: ["Armed assailant and firearm discharge", "Gun was pointed at the worker's head", "Violence prevention and escape controls failed", "Fatal gunshot injury", "The worker faced a loaded firearm aimed at the head before it discharged."],
  PRESSURE_WASHER: ["Pressurized wash-water contact", "Jet contacted the worker's leg", "Wand handling failed", "Injection severity depends on pressure", "The report omits jet pressure and penetration depth needed to determine SIF-level injection potential."],
  SAW_CONTACT: ["Operating table-saw blade", "Worker reached near the blade to clear scrap", "Guarding and safe jam-clearing controls failed", "Life-altering amputation or draw-in", "Clearing material beside an energized saw blade exposed the worker to uncontrolled cutting energy."],
  LIFT_FAN: ["Boom lift moving into an industrial ceiling fan", "Elevated worker was carried into rotating blades", "Lift travel and overhead-clearance controls failed", "Fatal fall or severe laceration", "The bucket entered an operating fan's sweep while the worker was elevated."],
  FORK_IMPALE: ["Raised forklift fork at head height", "Worker contacted the fork at the eye", "Fork position and pedestrian-clearance controls failed", "Blindness or penetrating head injury", "An exposed raised fork created an impalement hazard at the worker's head and eye level."],
  SPLINTER: ["Wooden-crate splinter", "Splinter penetrated the worker's thigh", "Material condition and handling controls failed", "Localized puncture", "A crate splinter caused a localized wound without credible fatal or permanent whole-body consequence."],
  ROUGH_RIDE: ["Water truck striking a pothole", "Driver was jarred in the seat", "Road maintenance or ride control was inadequate", "Musculoskeletal injury", "A pothole jolt without collision, rollover, or ejection does not establish credible SIF impact energy."],
  PRESSURE_SHRAPNEL: ["Trapped well pressure and shrapnel", "Observers stood in the valve debris path", "Depressurization and exclusion-zone controls failed", "Fatal penetrating or blunt-force trauma", "Trapped pressure expelled metal and valve parts through the occupied area."],
  PRESSURE_HOSE: ["Pressurized flexible-hose release", "Hose struck the worker's chest and abdomen", "Depressurization and restraint controls failed", "Fatal blunt trauma or internal injury", "A disconnected pressurized hose whipped into the worker's torso."],
  STEAM_PROJECTILE: ["Steam cleaning and expelled metal fitting", "Worker was struck in the head and hands", "Component retention and pressure controls failed", "Fatal head trauma or burns", "Steam pressure propelled a component from the tank toward the worker's head."],
  PUMP_PROJECTILE: ["Pump plunger expelled during maintenance", "Worker was in the plunger's path", "Stored-energy restraint failed", "Fatal projectile strike or crushing", "The plunger was propelled from the pump through an occupied work position."],
  CHAIN_SNAPBACK: ["Failed chain under excavator tension", "Worker stood beside the pulled auger", "Chain integrity and snapback-zone controls failed", "Fatal head strike or penetrating injury", "The loaded chain failed and recoiled directly into the worker's face."],
  HYDRAULIC_PROJECTILE: ["Separated hydraulic fitting and sleeve", "Two workers were struck near the cylinder", "Pressure containment and component retention failed", "Fatal projectile or injection injury", "Hydraulic components separated and became projectiles in an occupied area."],
  JACK_COLLAPSE: ["Jack collapse during wheel work", "Worker's hand was beside supported vehicle components", "Secondary support and clearance controls failed", "Fatal crushing by unsupported equipment", "Jack failure could drop the supported vehicle or wheel assembly onto the worker."],
  SUPPORTED_PLATFORM: ["Heavy platform on jack stands and sawhorses", "Worker adjusted a shim at the support point", "Stable support and exclusion controls failed", "Crushing by platform collapse", "Dislodging the shim released a supported platform immediately beside the worker."],
  PIPE_RACK_FALL: ["Rolling pipe at an elevated rack edge", "Worker's foot was caught and both worker and pipe fell", "Pipe restraint and safe-position controls failed", "Fatal fall or crushing by pipe", "The worker fell from the rack together with an uncontrolled pipe."],
  BOP_TIP: ["Unstable blowout preventer", "Worker was beside the BOP as it fell", "Stability and handling controls failed", "Fatal crushing by heavy well-control equipment", "The BOP tipped into the occupied work area and could have crushed the worker's body."],
  UNDER_LOAD: ["Worker positioned beneath or between an inadequately supported load", "Worker's hand was under the load", "Blocking, support, and exclusion controls failed", "Fatal crushing if the load drops", "The task placed the worker under an unstable heavy load rather than using secure blocking."],
  RIG_FLOOR_COLLAPSE: ["Falling derrick floor", "Workers were beneath or trying to restrain the floor", "Structural support and exclusion controls failed", "Fatal chest crushing or struck-by injury", "A derrick floor fell onto personnel during maintenance."],
  FORK_DROP: ["Released rough-terrain forklift fork", "Worker stood beside the falling fork", "Restraint and drop-zone controls failed", "Fatal crushing by heavy fork", "The untied heavy fork dropped into an occupied area."],
  TUBING_BOUNCE: ["Uncontrolled bouncing tubing joint", "Worker grabbed tubing at floor level", "Tubing-handling and hands-free controls failed", "Crushing by long heavy tubing", "The tubing was intentionally allowed to bounce where a worker then handled it by hand."],
  ROLLING_POLE: ["Utility pole rolling from an unsecured flatbed load", "Driver was beside the load when the last strap was removed", "Load-restraint and unloading-zone controls failed", "Fatal whole-body crushing", "Removing the last restraint released a heavy pole directly onto the worker."],
  ROLLING_LOCAL: ["Small pipe or collar rolling during manual handling", "A hand or foot was at the rolling interface", "Chocking and hand-position controls failed", "Localized digit or foot injury", "The described rolling geometry is confined to an extremity without credible whole-body crushing exposure."],
  PLATFORM_PIPE: ["Supported platform collapse with nearby pipe", "Worker stood on or beside the platform and pipe", "Platform support and load-control measures failed", "Crushing or serious fall injury", "The combined platform collapse and pipe movement created credible full-body crush and fall exposure."],
  ROLLING_PIPE: ["Uncontrolled heavy pipe or collar", "Worker occupied the pipe's roll path", "Chocking, stability, and exclusion controls failed", "Fatal or life-altering crushing", "The heavy tubular could continue rolling across the worker's body."],
  WIRE_SNAP: ["Tensioned barbed wire loaded by powered equipment", "Worker was in the recoil path", "Tension control and exclusion-zone controls failed", "Serious penetrating or laceration injury", "Powered tension could release the wire into personnel with severe strike and penetration energy."],
  PIPE_LINER: ["Powered pipe-liner alignment and sudden pipe movement", "Worker leaned over the pipe at the movement point", "Hands-free alignment and exclusion controls failed", "Fatal head or torso strike", "Unexpected powered pipe movement could strike or crush the worker leaning over the interface."],
  RIG_FLOOR_PANEL: ["Large rig-floor wing or panel falling", "Worker supported or handled the panel in its fall path", "Mechanical support and drop-zone controls failed", "Fatal crushing or struck-by injury", "The large floor panel fell into an occupied handling position."],
  TIRE_ENERGY: ["Inflated tire and wheel assembly during airing", "Worker was adjacent to the inflation zone", "Inflation restraint and separation controls failed", "Fatal blast or projectile injury", "Stored pneumatic energy in a tire assembly can release components with fatal force."],
  GATE_ROLLER: ["Moving gate and powered or rolling mechanism", "Worker inserted a hand while releasing the mechanism", "Isolation, guarding, and safe hand-position controls failed", "Entanglement or traumatic amputation", "The hand was placed in an active gate mechanism capable of drawing in or amputating."],
  HEAVY_DOOR: ["Large vee-door or similar heavy panel swinging free", "Worker was at the door and catwalk interface", "Door securement and exclusion controls failed", "Fatal crushing or struck-by injury", "Loss of control of the heavy door exposed the worker to full-body strike and crush energy."],
  OUTRIGGER: ["Powered crane outrigger extension", "Worker stood in the outrigger travel path", "Spotting and exclusion-zone controls failed", "Fatal crushing against equipment or structures", "The powered outrigger could trap the worker's body against a fixed object."],
  CART_TIP: ["Loaded cart and drilling motor tipping", "Workers were beside or beneath the unstable load", "Load stability and securement controls failed", "Fatal crushing by the motor or cart", "The heavy motor and cart tipped into an occupied area."],
  LOAD_IN_CAB: ["Heavy pump sliding from skid-steer forks", "Operator occupied the cab in the load's travel path", "Load securement and fork-backrest controls failed", "Fatal crushing or impalement", "The unsecured pump entered the occupied cab with fatal impact potential."],
  UNRESTRAINED_CARGO: ["Moving truck with loose pipe-handling cargo", "Worker rode in the cargo bed beside the moving load", "Occupant separation and cargo restraint failed", "Fatal struck-by, crushing, or ejection", "The worker shared an unrestrained cargo space with heavy moving equipment during vehicle travel."],
  TONG_SNAP: ["Snub-line failure driving power tongs", "Worker occupied the tong swing path", "Line integrity and exclusion-zone controls failed", "Fatal strike or crushing injury", "Released line energy propelled the tongs through the worker's body position."],
  TRENCHER_SWING: ["Powered trencher stinger moving a fence", "Worker held the fence in the movement path", "Separation and hands-free control failed", "Severe struck-by or entanglement injury", "Powered equipment transferred motion through the fence directly to the exposed worker."],
  STRUCTURE_COLLAPSE: ["Steel hut or small structure blown over", "Workers were inside or beside the structure", "Wind securement and shelter controls failed", "Fatal structural crushing", "Wind overturned an occupied steel structure, creating credible fatal collapse exposure."],
  TORNADO: ["Tornado impact on an occupied office trailer", "Personnel remained inside the trailer", "Severe-weather warning and shelter controls failed", "Fatal collapse or projectile injury", "A tornado destroyed the occupied trailer, creating obvious fatal structural and debris hazards."],
  MASS_STING: ["Multiple bee stings to face, neck, and torso", "Worker was swarmed and lost consciousness", "Insect-hazard avoidance and emergency-response controls failed", "Fatal anaphylaxis or airway compromise", "Widespread stings with loss of consciousness establish credible fatal allergic and airway consequences."],
};

function csvEscape(value) {
  const text = value == null ? "" : String(value);
  return /[",\r\n]/.test(text) ? `"${text.replaceAll('"', '""')}"` : text;
}

function toCsv(rows) {
  return rows.map(row => row.map(csvEscape).join(",")).join("\r\n") + "\r\n";
}

async function main() {
  const csvText = await fs.readFile(queuePath, "utf8");
  const workbook = await Workbook.fromCSV(csvText, { sheetName: "Queue" });
  const sheet = workbook.worksheets.getItem("Queue");
  const values = sheet.getUsedRange(true).values;
  const headers = values[0].map(String);
  const queue = values.slice(1).filter(row => row.some(value => value !== null && value !== "")).map(row => Object.fromEntries(headers.map((header, index) => [header, row[index] == null ? "" : String(row[index])])));
  if (queue.length !== 500) throw new Error(`Expected 500 queue records, found ${queue.length}`);
  const queueIds = new Set(queue.map(row => row.candidate_id));
  const decisionIds = Object.keys(decisions);
  if (queueIds.size !== queue.length) throw new Error("Duplicate candidate IDs in the source queue");
  if (decisionIds.length !== queue.length || decisionIds.some(id => !queueIds.has(id))) throw new Error("Decision IDs do not exactly match the source queue");
  const outputHeader = ["candidate_id", "source", "source_record_id", "narrative", "ai_pass_a_label", "ai_pass_a_confidence", "ai_pass_a_hazard", "ai_pass_a_exposure", "ai_pass_a_barrier_failure", "ai_pass_a_credible_consequence", "ai_pass_a_reason", "ai_pass_a_framework_version"];
  const labels = queue.map(row => {
    const decision = decisions[row.candidate_id];
    if (!decision) throw new Error(`Missing decision for ${row.candidate_id}`);
    const [labelCode, confidence, evidenceCode] = decision;
    const fields = evidence[evidenceCode];
    if (!fields) throw new Error(`Missing evidence taxonomy ${evidenceCode}`);
    const label = labelCode === "S" ? "SIF_POTENTIAL" : labelCode === "N" ? "NON_SIF_POTENTIAL" : "UNCERTAIN";
    return [row.candidate_id, row.source, row.source_record_id, row.narrative, label, confidence.toFixed(2), ...fields, "AI_SOL_XHIGH_PASS_A"];
  });
  const ids = labels.map(row => row[0]);
  if (new Set(ids).size !== ids.length) throw new Error("Duplicate candidate IDs in output");
  if (labels.some(row => row.length !== outputHeader.length)) throw new Error("Malformed output row");
  const validLabels = new Set(["SIF_POTENTIAL", "NON_SIF_POTENTIAL", "UNCERTAIN"]);
  if (labels.some(row => !validLabels.has(row[4]) || !Number.isFinite(Number(row[5])) || Number(row[5]) < 0 || Number(row[5]) > 1)) throw new Error("Invalid label or confidence");
  if (labels.some(row => [row[0], row[4], row[6], row[7], row[8], row[9], row[10], row[11]].some(value => String(value).trim() === ""))) throw new Error("Missing required output field");
  const taxonomyLabels = new Map();
  for (const [labelCode, , evidenceCode] of Object.values(decisions)) {
    if (!taxonomyLabels.has(evidenceCode)) taxonomyLabels.set(evidenceCode, labelCode);
    else if (taxonomyLabels.get(evidenceCode) !== labelCode) throw new Error(`Inconsistent labels for evidence taxonomy ${evidenceCode}`);
  }
  const narrativeLabels = new Map();
  for (const row of labels) {
    const normalized = row[3].toLowerCase().replace(/\s+/g, " ").trim();
    if (!narrativeLabels.has(normalized)) narrativeLabels.set(normalized, row[4]);
    else if (narrativeLabels.get(normalized) !== row[4]) throw new Error(`Conflicting labels for duplicate narrative ${row[0]}`);
  }
  const uncertain = labels.filter(row => row[4] === "UNCERTAIN");
  const confidences = labels.map(row => Number(row[5]));
  const counts = Object.fromEntries(["SIF_POTENTIAL", "NON_SIF_POTENTIAL", "UNCERTAIN"].map(label => [label, labels.filter(row => row[4] === label).length]));
  const summary = { total: labels.length, ...counts, "mean confidence": Number((confidences.reduce((a, b) => a + b, 0) / confidences.length).toFixed(4)), "high-confidence count": confidences.filter(value => value >= 0.80).length, "low-confidence count": confidences.filter(value => value < 0.60).length };
  await fs.mkdir(outputDir, { recursive: true });
  await fs.writeFile(path.join(outputDir, "sol_pass_a_labels.csv"), toCsv([outputHeader, ...labels]), "utf8");
  await fs.writeFile(path.join(outputDir, "sol_pass_a_uncertain.csv"), toCsv([outputHeader, ...uncertain]), "utf8");
  await fs.writeFile(path.join(outputDir, "sol_pass_a_summary.json"), JSON.stringify(summary, null, 2) + "\n", "utf8");
  const outputWorkbook = await Workbook.fromCSV(toCsv([outputHeader, ...labels]), { sheetName: "Labels" });
  const check = await workbook.inspect({ kind: "table", range: "Queue!A1:K6", include: "values", tableMaxRows: 6, tableMaxCols: 11, maxChars: 2000 });
  const outputCheck = await outputWorkbook.inspect({ kind: "table", range: "Labels!A1:L6", include: "values", tableMaxRows: 6, tableMaxCols: 12, maxChars: 3000 });
  console.log(check.ndjson);
  console.log(outputCheck.ndjson);
  console.log(JSON.stringify(summary));
}

await main();
