-- SIF Sentinel application persistence.  The FastAPI service uses the
-- server-only Supabase secret key for these tables; browser clients do not.
create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text,
  role text not null default 'demo' check (role in ('demo', 'reviewer', 'admin')),
  created_at timestamptz not null default now()
);

create table if not exists public.incidents (
  id text primary key,
  report_date date,
  site text,
  activity text,
  narrative text not null,
  source text,
  source_id text,
  normalized_narrative text,
  sif_probability double precision,
  risk text,
  high_potential boolean,
  sif_potential boolean,
  sif_label_status text,
  analysis jsonb,
  review_status text,
  reviewer text,
  review_comment text,
  created_at timestamptz not null default now(),
  created_by_user_id uuid references auth.users(id) on delete set null,
  report_type text not null default 'Unspecified',
  import_batch_id text
);

create table if not exists public.alerts (
  id text primary key,
  title text,
  detail text,
  severity text,
  status text,
  site text,
  created_at timestamptz not null default now()
);

create table if not exists public.review_history (
  id bigint generated by default as identity primary key,
  incident_id text not null references public.incidents(id) on delete cascade,
  outcome text not null,
  reviewer text,
  reviewer_user_id uuid references auth.users(id) on delete set null,
  comment text,
  timestamp timestamptz not null default now(),
  previous_outcome text,
  new_outcome text,
  screening_version text
);

create index if not exists incidents_report_date_idx on public.incidents (report_date desc, created_at desc);
create index if not exists incidents_site_idx on public.incidents (site);
create index if not exists incidents_activity_idx on public.incidents (activity);
create index if not exists incidents_review_status_idx on public.incidents (review_status);
create index if not exists incidents_sif_potential_idx on public.incidents (sif_potential);
create index if not exists incidents_source_id_idx on public.incidents (source_id);
create index if not exists incidents_normalized_narrative_idx on public.incidents (normalized_narrative);
create index if not exists incidents_import_batch_idx on public.incidents (import_batch_id);
create index if not exists review_history_incident_idx on public.review_history (incident_id, id);
create index if not exists alerts_status_idx on public.alerts (status, created_at desc);

alter table public.profiles enable row level security;
alter table public.incidents enable row level security;
alter table public.alerts enable row level security;
alter table public.review_history enable row level security;

drop policy if exists "users can read their own profile" on public.profiles;
create policy "users can read their own profile" on public.profiles
  for select to authenticated using (id = auth.uid());

-- No browser policy is granted for incidents, alerts, or review_history.
-- FastAPI authorizes each request and persists with the server-only key.
